import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import type { BoothConfigBundle, SpinResponse } from '@oto/shared';
import type { BoothStatus } from '../booth/contract';
import { STAFF_COPY } from '../copy';

interface Props {
  open: boolean;
  onClose: () => void;
  transport: 'fake' | 'http';
  configVersion: number | null;
  bundle: BoothConfigBundle | null;
  status: BoothStatus | null;
  lastSpin: SpinResponse | null;
  /** Presses whose prize did not match this page's own array (see App). */
  mismatches: number;
  /** The last failure's code, or null. Codes only — never a server's prose (D15). */
  lastErrorCode: string | null;
  /** The last few key events, so an unexpected button mapping is visible. */
  inputLog: string[];
  /**
   * Draw once through **the same call the red button makes**, with the
   * simulate flag set. Supplied by the caller so that this overlay cannot
   * acquire a second copy of the draw — a distribution table generated by
   * locally reimplemented arithmetic measures the reimplementation, proves
   * nothing about the booth, and is exactly the one-sided test this project
   * has shipped five times.
   */
  simulateSpin: () => Promise<SpinResponse>;
}

const RUN_SIZE = 200;
/** Diagnostics on a booth television close themselves (D16). */
const AUTO_CLOSE_MS = 60_000;
/** The threshold this ticket's acceptance criterion names. */
const DEVIATION_THRESHOLD_PP = 5;

/**
 * How far a FAIR draw is expected to wander, in percentage points: the 95%
 * interval, 1.96 standard errors of a binomial proportion.
 *
 * This column exists because the ±5 pp threshold above is not a test of
 * fairness at two hundred draws, and reading it as one leads somebody to
 * "correct" a draw that is already correct. For the 27.5% slice the standard
 * error at n=200 is 3.2 pp, so its 95% interval is ±6.2 — wider than the
 * threshold on its own. Across six prizes a perfectly fair wheel puts at
 * least one of them outside ±5 pp in roughly one run in three (normal
 * approximation, seeded weights). A red cell is a reason to run it again, not
 * a finding.
 */
function samplingBandPp(expectedPct: number, draws: number): number {
  if (draws <= 0) return 0;
  const p = expectedPct / 100;
  return 1.96 * Math.sqrt((p * (1 - p)) / draws) * 100;
}

interface Tally {
  prizeId: string;
  name: string;
  expectedPct: number;
  observed: number;
}

export function DebugOverlay(props: Props) {
  const { open, onClose, bundle, simulateSpin } = props;
  const [running, setRunning] = useState(false);
  const [done, setDone] = useState(0);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [ran, setRan] = useState(0);
  const [failed, setFailed] = useState(0);
  const [activity, setActivity] = useState(() => Date.now());
  const cancelled = useRef(false);

  const touch = useCallback(() => setActivity(Date.now()), []);

  useEffect(() => {
    if (!open) return;
    const timer = window.setTimeout(onClose, AUTO_CLOSE_MS);
    return () => window.clearTimeout(timer);
  }, [open, activity, onClose]);

  useEffect(() => {
    if (open) return;
    // Leaving the overlay abandons a run in progress. Nothing was written, so
    // there is nothing to unwind.
    cancelled.current = true;
    setRunning(false);
  }, [open]);

  const run = useCallback(async () => {
    if (running) return;
    cancelled.current = false;
    setRunning(true);
    setDone(0);
    setRan(0);
    setFailed(0);
    setCounts({});
    const tally: Record<string, number> = {};
    let completed = 0;
    let errors = 0;
    for (let i = 0; i < RUN_SIZE; i += 1) {
      if (cancelled.current) break;
      try {
        const spin = await simulateSpin();
        tally[spin.prizeId] = (tally[spin.prizeId] ?? 0) + 1;
        completed += 1;
      } catch {
        // A refusal mid-run is a fact about the booth, not a reason to stop:
        // a wheel whose every prize has hit its cap refuses every press, and
        // a table of 200 refusals is the answer to "why is nobody winning".
        errors += 1;
      }
      // Every tenth, rather than every draw: 200 renders in a row on a Pi
      // under a television is the kind of thing that makes a booth stutter
      // while somebody is watching it.
      if (i % 10 === 9 || i === RUN_SIZE - 1) {
        setDone(i + 1);
        setCounts({ ...tally });
        setRan(completed);
        setFailed(errors);
      }
    }
    setRunning(false);
    touch();
  }, [running, simulateSpin, touch]);

  const rows = useMemo<Tally[]>(() => {
    if (!bundle) return [];
    // Expected is the published weight renormalised over the prizes this page
    // can see are active — the only part of eligibility a bundle carries. The
    // box also excludes a prize that has hit its daily cap or run out of
    // stock (D5), and when it does, that prize's expected share here is too
    // high and every other row's is too low. The line under the table says so.
    const active = bundle.prizes.filter((prize) => prize.active);
    const total = active.reduce((sum, prize) => sum + prize.weightBp, 0);
    return active.map((prize) => ({
      prizeId: prize.id,
      name: prize.nameEn,
      expectedPct: total === 0 ? 0 : (prize.weightBp / total) * 100,
      observed: counts[prize.id] ?? 0,
    }));
  }, [bundle, counts]);

  if (!open) return null;

  const { transport, configVersion, status, lastSpin, mismatches, lastErrorCode, inputLog } = props;

  return (
    <div className="k-debug" data-booth-panel="debug" onClick={touch} role="presentation">
      <div className="k-debug-head">
        <span>{STAFF_COPY.debugTitle}</span>
        <button type="button" className="k-panel-btn" onClick={onClose}>
          {STAFF_COPY.cancel}
        </button>
      </div>

      <dl className="k-debug-facts">
        <Fact
          label="Source"
          value={transport === 'fake' ? 'built-in fake (not a booth)' : 'booth service'}
        />
        <Fact
          label="Config version"
          value={configVersion === null ? 'none' : `v${configVersion}`}
        />
        <Fact label="Bundle schema" value={bundle === null ? '—' : `v${bundle.schemaVersion}`} />
        <Fact label="Layout" value={bundle?.layout.name ?? '—'} />
        <Fact label="Button key" value={bundle?.settings.buttonKey ?? '—'} />
        <Fact label="Link" value={status === null ? '—' : status.online ? 'online' : 'offline'} />
        <Fact label="Printer" value={status?.printerReachable ?? '—'} />
        <Fact label="Paper" value={status?.paperStatus ?? '—'} />
        <Fact label="Queue depth" value={status === null ? '—' : String(status.vouchersPending)} />
        <Fact
          label="Caps reached"
          value={status === null ? '—' : String(status.dailyCapsReached.length)}
        />
        <Fact label="Staff signed in" value={status?.staffSignedIn ? 'yes' : 'no'} />
        <Fact label="Last spin" value={formatTime(status?.lastSpinAt ?? null)} />
        <Fact
          label="Last spin print"
          value={
            lastSpin === null
              ? '—'
              : lastSpin.printState + (lastSpin.clockSuspect ? ' · clock suspect' : '')
          }
        />
        {/* Whether the spin was attributed, never to whom: the account id is
            opaque, but a booth television is read by the public and an
            identifier is still an identifier (D15). */}
        <Fact
          label="Last spin attributed"
          value={lastSpin === null ? '—' : lastSpin.staffAccountId === null ? 'no' : 'yes'}
        />
        <Fact label="Config mismatches" value={String(mismatches)} />
        <Fact label="Last error" value={lastErrorCode ?? 'none'} />
      </dl>

      <div className="k-debug-run">
        <button type="button" className="k-panel-btn" onClick={() => void run()} disabled={running}>
          {running ? `Spinning ${done} / ${RUN_SIZE}…` : `Spin ${RUN_SIZE} times`}
        </button>
        <span className="k-debug-note">{STAFF_COPY.debugSimulated}</span>
      </div>

      {ran > 0 && (
        <>
          <table className="k-debug-table">
            <thead>
              <tr>
                <th>Prize</th>
                <th>Expected</th>
                <th>Observed</th>
                <th>Deviation</th>
                <th>Chance alone</th>
              </tr>
            </thead>
            <tbody>
              {rows.map((row) => {
                const observedPct = ran === 0 ? 0 : (row.observed / ran) * 100;
                const deviation = observedPct - row.expectedPct;
                return (
                  <tr key={row.prizeId}>
                    <td>{row.name}</td>
                    <td>{row.expectedPct.toFixed(1)}%</td>
                    <td>
                      {observedPct.toFixed(1)}% ({row.observed})
                    </td>
                    <td
                      className={
                        Math.abs(deviation) > DEVIATION_THRESHOLD_PP ? 'k-debug-off' : undefined
                      }
                    >
                      {deviation >= 0 ? '+' : ''}
                      {deviation.toFixed(1)} pp
                    </td>
                    <td>±{samplingBandPp(row.expectedPct, ran).toFixed(1)} pp</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          <p className="k-debug-note">
            {ran} draw{ran === 1 ? '' : 's'} counted{failed > 0 ? `, ${failed} refused` : ''}.
            Expected is the published weight over active prizes; a prize the booth excluded for a
            daily cap or stock will read low here and push every other row high. The last column is
            how far a fair draw wanders on its own at this many draws — a deviation inside it is
            noise, not a thumb on the scale.
          </p>
        </>
      )}

      <div className="k-debug-input">
        {inputLog.length === 0 ? <span className="k-debug-note">No key events yet</span> : null}
        {inputLog.map((line, index) => (
          <div key={`${index}-${line}`}>{line}</div>
        ))}
      </div>
    </div>
  );
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div className="k-debug-fact">
      <dt>{label}</dt>
      <dd>{value}</dd>
    </div>
  );
}

function formatTime(iso: string | null): string {
  if (iso === null) return '—';
  const when = new Date(iso);
  if (Number.isNaN(when.getTime())) return '—';
  return new Intl.DateTimeFormat('en-GB', {
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  }).format(when);
}
