-- SCRUM-502 — the prepaid food lines of one supervised stay, found by the stay.
-- Landed as 0069, after the benefit credentials migration (0068); the
-- snapshot was regenerated at landing so its chain and tables carry 0068's.
--
-- The platform counts what a box's own completed sales have served from each
-- in-park stay's prepaid food (`boxPrepaidFiled`) every time it builds that
-- box's check-in copy, and what open orders hold (`prepaidHeldOnOpenOrders`).
-- Both look a stay up by `payload -> 'prepaid' ->> 'checkinId'` on
-- `pos.sale_line`, which no index covered, so the lookup read every food line
-- the park had sold and slowed as the history grew. Partial: only lines that
-- name a stay are in it. Expand-only.
CREATE INDEX "sale_line_prepaid_stay_idx" ON "pos"."sale_line" USING btree ((payload -> 'prepaid' ->> 'checkinId')) WHERE (payload -> 'prepaid' ->> 'checkinId') is not null;