/**
 * The terminal fixtures, and where they come from (S2-10a).
 *
 * Every file in this directory is **the bytes that actually crossed the wire**
 * between the adapter in `src/terminal/` and the simulator in the same
 * directory — recorded by tee-ing the channel, not typed out by hand and not
 * copied from a vendor document. That matters twice over:
 *
 *  - Nothing from `imports/` is copied into the repository. The vendor PDF and
 *    the Digio HTML are local reference; what is committed here is our own
 *    encoder's output, with a citation in each header saying which table or
 *    example it was built from.
 *  - A fixture generated by the code under test pins DRIFT, not correctness.
 *    Correctness is pinned separately and harder, in `terminal-digio.test.ts`:
 *    the encoder reproduces the three frames the vendor specification prints
 *    correctly, byte for byte, including their CRCs.
 *
 * GHL RESPONSES ARE MARKED INFERRED, every one of them. The vendor PDF prints
 * exactly one literal message (p.18, a request builder) and no response XML
 * anywhere, so the element names, types and requiredness in the response
 * fixtures are cited from the parameter tables while the envelope and the
 * ordering are reconstructed from the sample's convention. One captured real
 * exchange is wanted before the GHL adapter is called verified.
 *
 * Regenerate with:
 *   node --experimental-strip-types packages/box-agent/test/fixtures/terminal/generate.ts --write
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import type { PaymentTerminal, TerminalChannel } from '../../../src/terminal/contract';
import { toHex } from '../../../src/terminal/digio';
import { digioTerminal } from '../../../src/terminal/digio';
import { ghlTerminal } from '../../../src/terminal/ghl';
import { createDigioSimulator } from '../../../src/terminal/simulator-digio';
import { createGhlSimulator } from '../../../src/terminal/simulator-ghl';
import { formatRef } from '../../../src/terminal/counter';

const decoder = new TextDecoder('utf-8');

/**
 * The park's own identities, from `docs/architecture/DEVICE_INVENTORY.md:38-41`
 * and the seed. Device identifiers already in the repository, not credentials.
 */
export const NEXGO_TID = '65703235';
export const NEXGO_MID = '4648434010';
export const PAX_SERIAL = '1854355548';

/** Fixed so a regenerated fixture is the same bytes, not a new timestamp. */
const FIXED_NOW = new Date('2026-09-23T07:05:00.000Z');
const GHL_DEVICE_ID = '018f0000-0000-7000-8000-0000000edc01';
const PAX_DEVICE_ID = '018f0000-0000-7000-8000-0000000edc03';
const BUSINESS_DATE = '2026-09-23';
const CASHIER = 'Jane Doe';
/**
 * A PLACEHOLDER, and it has no digits in it on purpose.
 *
 * The Digio specification prints a fixed void password in its own §5.5. A
 * credential in a vendor document is still a credential: the real one is
 * configuration on the box, and nothing under `packages/` or `apps/` — fixtures
 * included — carries it.
 */
const VOID_PASSWORD_PLACEHOLDER = 'VOIDPW';

export interface Fixture {
  /** Relative to this directory. */
  file: string;
  header: string[];
  /** Hex for a Digio frame, the XML string for a GHL message. */
  body: string;
}

interface Transcript {
  sent: Uint8Array[];
  received: Uint8Array[];
}

/** Tee a channel so the fixture is what crossed it, in both directions. */
function record(channel: TerminalChannel, into: Transcript): TerminalChannel {
  return {
    async write(bytes) {
      into.sent.push(bytes);
      return channel.write(bytes);
    },
    async readFrame(scan, timeoutMs) {
      const frame = await channel.readFrame(scan, timeoutMs);
      if (frame) into.received.push(frame);
      return frame;
    },
    discard: () => channel.discard(),
    close: () => channel.close(),
  };
}

function refs(protocol: 'ghl_linkpos' | 'digio_tlv', deviceId: string): () => Promise<string> {
  let seq = 0;
  return async () => {
    seq += 1;
    return formatRef(protocol, { deviceId, protocol, businessDate: BUSINESS_DATE }, seq);
  };
}

function hexOf(bytes: Uint8Array | undefined): string {
  return bytes ? toHex(bytes) : '';
}

function xmlOf(bytes: Uint8Array | undefined): string {
  return bytes ? decoder.decode(bytes) : '';
}

export async function buildFixtures(): Promise<Fixture[]> {
  const out: Fixture[] = [];

  // --- GHL ------------------------------------------------------------------

  const ghlCitation = [
    'Source: GHL "SMART POS API - Integration POS to SmartEDC for Siam Commercial',
    '  Bank PCL" v1.4 (Jan 2025). Element order from the C# sample on p.18, the',
    '  only literal message in the document; field names, types and requiredness',
    '  from the parameter tables named per fixture.',
    'Recorded from the wire between src/terminal/ghl.ts and simulator-ghl.ts.',
  ];

  async function ghlExchange(
    run: (terminal: PaymentTerminal) => Promise<unknown>,
    setup?: (sim: ReturnType<typeof createGhlSimulator>) => void,
  ): Promise<Transcript> {
    const sim = createGhlSimulator({
      deviceId: GHL_DEVICE_ID,
      label: 'EDC 1 (NEXGO N5)',
      terminalId: NEXGO_TID,
      merchantId: NEXGO_MID,
      now: () => FIXED_NOW,
    });
    setup?.(sim);
    const transcript: Transcript = { sent: [], received: [] };
    const terminal = ghlTerminal({
      deviceId: GHL_DEVICE_ID,
      label: 'EDC 1 (NEXGO N5)',
      terminalId: NEXGO_TID,
      merchantId: NEXGO_MID,
      open: async () => record(sim.connect(), transcript),
      nextRef: refs('ghl_linkpos', GHL_DEVICE_ID),
      now: () => FIXED_NOW,
      cashier: CASHIER,
    });
    await run(terminal);
    return transcript;
  }

  const cardSale = await ghlExchange((terminal) =>
    terminal.sale({ attemptId: 'fixture', amountSatang: 10025, tender: 'card' }),
  );
  out.push({
    file: 'ghl/sale-request-card.xml',
    header: [
      'GHL LinkPOS - card SALE request.',
      'Fields: p.8 request table (trade_type CARD, amount Decimal, pos_ref_no',
      '  String(20) unique, transaction_type SALE). pos_ref_no is minted at 12',
      '  characters: the intersection of the document’s 20 (SALE), 12 (QUERY)',
      '  and 32 (VOID).',
      ...ghlCitation,
    ],
    body: xmlOf(cardSale.sent[0]),
  });
  out.push({
    file: 'ghl/sale-response-card-approved.xml',
    header: [
      'GHL LinkPOS - card SALE response, approved.',
      'INFERRED FROM THE PARAMETER TABLES: the vendor PDF prints no response XML',
      '  anywhere. Field set from p.8 (pos_ref_no, response_code, response_msg,',
      '  invoice_no, card_no masked, amount, card_approval_code); the <xml>',
      '  wrapper and the ordering follow the p.18 sample’s convention.',
      'response_code 00 is the ISO space, which a CARD SALE alone answers in.',
      'card_no carries a masked placeholder; the adapter keeps four digits of it.',
      ...ghlCitation,
    ],
    body: xmlOf(cardSale.received[0]),
  });

  const declined = await ghlExchange(
    (terminal) => terminal.sale({ attemptId: 'fixture', amountSatang: 10025, tender: 'card' }),
    (sim) => sim.setOutcome('declined'),
  );
  out.push({
    file: 'ghl/sale-response-card-declined.xml',
    header: [
      'GHL LinkPOS - card SALE response, declined.',
      'INFERRED FROM THE PARAMETER TABLES (see the approved fixture).',
      'response_code 05 "Do not honor" from the ISO table, p.8.',
      ...ghlCitation,
    ],
    body: xmlOf(declined.received[0]),
  });

  const partial = await ghlExchange(
    (terminal) => terminal.sale({ attemptId: 'fixture', amountSatang: 10025, tender: 'card' }),
    (sim) => sim.setOutcome('partial', { approvedSatang: 5000 }),
  );
  out.push({
    file: 'ghl/sale-response-card-partial.xml',
    header: [
      'GHL LinkPOS - card SALE response, PARTIAL approval.',
      'INFERRED FROM THE PARAMETER TABLES (see the approved fixture).',
      'response_code 10 "Partial approval", p.8, with an amount below the request.',
      'The adapter refuses the sale on this and voids the tender: the platform',
      '  cannot take the difference.',
      ...ghlCitation,
    ],
    body: xmlOf(partial.received[0]),
  });

  const qrSale = await ghlExchange((terminal) =>
    terminal.sale({
      attemptId: 'fixture',
      amountSatang: 10025,
      tender: 'qr',
      wallet: 'THAIQRCODE',
    }),
  );
  out.push({
    file: 'ghl/sale-request-qr.xml',
    header: [
      'GHL LinkPOS - Thai QR SALE request.',
      'Fields: p.11 request table. service_type SHOWQR means the guest scans a',
      '  code the TERMINAL draws - this dialect never returns a payload.',
      ...ghlCitation,
    ],
    body: xmlOf(qrSale.sent[0]),
  });
  out.push({
    file: 'ghl/sale-response-qr-approved.xml',
    header: [
      'GHL LinkPOS - Thai QR SALE response, approved.',
      'INFERRED FROM THE PARAMETER TABLES: p.11 response table (pos_ref_no,',
      '  response_code, response_msg, transaction_id, invoice_no, amount). No',
      '  card_no and no card_approval_code on a wallet sale.',
      'response_code 00 here is the SmartEDC’s own 00/01 space, NOT the ISO',
      '  space the card fixture above answers in. Same field, two vocabularies.',
      ...ghlCitation,
    ],
    body: xmlOf(qrSale.received[0]),
  });

  const query = await ghlExchange((terminal) =>
    terminal.inquire({
      attemptId: 'fixture',
      tender: 'qr',
      wallet: 'THAIQRCODE',
      terminalRef: 'NOSUCHREF001',
    }),
  );
  out.push({
    file: 'ghl/query-request.xml',
    header: [
      'GHL LinkPOS - QUERY request.',
      'Fields: p.13. pos_ref_no is the ORIGINAL sale’s ("Same as Original Sale")',
      '  and not a fresh one - it is the lookup key.',
      'There is NO QUERY for trade_type CARD (p.13). The adapter refuses that',
      '  before a byte goes out, which is why the audited staff-confirmation',
      '  dialog is permanent for a NEXGO card rather than a fallback.',
      ...ghlCitation,
    ],
    body: xmlOf(query.sent[0]),
  });
  out.push({
    file: 'ghl/query-response-not-found.xml',
    header: [
      'GHL LinkPOS - QUERY response, no such transaction.',
      'INFERRED FROM THE PARAMETER TABLES: p.13-14.',
      'response_code 01 in the 00/01 space. The document names no "still',
      '  pending" code at all, which is an open question for GHL.',
      ...ghlCitation,
    ],
    body: xmlOf(query.received[0]),
  });

  const voided = await ghlExchange(async (terminal) => {
    const sale = await terminal.sale({
      attemptId: 'fixture',
      amountSatang: 10025,
      tender: 'card',
    });
    return terminal.void({
      attemptId: 'fixture',
      tender: 'card',
      amountSatang: 10025,
      tranRef: sale.invoiceNo ?? '',
      approvalCode: sale.approvalCode,
    });
  });
  out.push({
    file: 'ghl/void-request-card.xml',
    header: [
      'GHL LinkPOS - card VOID request.',
      'Fields: p.16. The key is invoice_no PLUS card_approval_code; pos_ref_no is',
      '  a FRESH reference for the void itself ("3rd party mobile app generates',
      '  to reference the transaction (Unique)"), never the sale’s.',
      'card_approval_code appears in no message the document prints - the p.18',
      '  sample has eight elements and not this one - so its position in the',
      '  envelope is reconstructed.',
      ...ghlCitation,
    ],
    body: xmlOf(voided.sent[1]),
  });
  out.push({
    file: 'ghl/void-response-card.xml',
    header: [
      'GHL LinkPOS - card VOID response.',
      'INFERRED FROM THE PARAMETER TABLES: p.16.',
      'response_code 00 is the 00/01 space: EVERY void answers there, including a',
      '  card’s, while a card SALE answers in the ISO space.',
      ...ghlCitation,
    ],
    body: xmlOf(voided.received[1]),
  });

  // --- Digio ----------------------------------------------------------------

  const digioCitation = [
    'Source: Digio "A920 Link-PoS-Spec" v2.21 (20 Oct 2025), section numbers as',
    '  printed there.',
    'Framing per §4: [3E 55][BER length][content][XOR CRC over header..content].',
    'THE CRC IS GENERATED, NEVER COPIED: seven of the ten complete frames the',
    '  document prints carry a CRC its own §4 rule does not produce.',
    'Recorded from the wire between src/terminal/digio.ts and simulator-digio.ts.',
  ];

  async function digioExchange(
    run: (terminal: PaymentTerminal) => Promise<unknown>,
    setup?: (sim: ReturnType<typeof createDigioSimulator>) => void,
  ): Promise<Transcript> {
    const sim = createDigioSimulator({
      deviceId: PAX_DEVICE_ID,
      label: 'EDC 3 (PAX A920Pro)',
      serialNumber: PAX_SERIAL,
      voidPassword: VOID_PASSWORD_PLACEHOLDER,
      now: () => FIXED_NOW,
    });
    setup?.(sim);
    const transcript: Transcript = { sent: [], received: [] };
    const terminal = digioTerminal({
      deviceId: PAX_DEVICE_ID,
      label: 'EDC 3 (PAX A920Pro)',
      terminalId: null,
      merchantId: null,
      open: async () => record(sim.connect(), transcript),
      nextRef: refs('digio_tlv', PAX_DEVICE_ID),
      now: () => FIXED_NOW,
      cashier: CASHIER,
      voidPassword: VOID_PASSWORD_PLACEHOLDER,
    });
    await run(terminal);
    return transcript;
  }

  const digioCard = await digioExchange((terminal) =>
    terminal.sale({ attemptId: 'fixture', amountSatang: 10050, tender: 'card' }),
  );
  out.push({
    file: 'digio/sale-request-card.hex',
    header: [
      'Digio - SALE request (A0), credit card.',
      'Tags from §5.4.1: 21 action A0, 01 amount in satang as ASCII digits, 03',
      '  POS user name, 04 six-digit reference, 05 payment type A1 (credit).',
      'Tag 05 is always sent: "if you not set default will be select payment type',
      '  screen", which would put the choice on the terminal instead of the till.',
      ...digioCitation,
    ],
    body: hexOf(digioCard.sent[0]),
  });
  out.push({
    file: 'digio/sale-response-card-approved.hex',
    header: [
      'Digio - SALE response (A1), approved.',
      'Tags from §5.4.2.1. Approved is response code 100 on tag 22 - three',
      '  characters, not 00.',
      'On THIS action the TID is tag 13 and the MID tag 14. On an A3 they are 16',
      '  and 17, and 13 means Ref3. That is why the parser has a table per action.',
      'Tag 09 is a masked card number and tag 0A a cardholder name, both carried',
      '  here so the adapter is seen keeping four digits of one and none of the',
      '  other. The card number is a placeholder.',
      ...digioCitation,
    ],
    body: hexOf(digioCard.received[0]),
  });

  const digioTimeout = await digioExchange(
    (terminal) => terminal.sale({ attemptId: 'fixture', amountSatang: 10050, tender: 'card' }),
    (sim) => sim.setOutcome('timeout'),
  );
  out.push({
    file: 'digio/sale-response-host-timeout.hex',
    header: [
      'Digio - SALE response, 401 Host timeout (§6.2).',
      'The terminal is alive and its own host is not, so whether the money moved',
      '  is unknown - a different fact from silence, and not a decline.',
      ...digioCitation,
    ],
    body: hexOf(digioTimeout.received[0]),
  });

  const digioQr = await digioExchange((terminal) =>
    terminal.sale({
      attemptId: 'fixture',
      amountSatang: 10050,
      tender: 'qr',
      requestQrPayload: true,
    }),
  );
  out.push({
    file: 'digio/sale-request-qr.hex',
    header: [
      'Digio - SALE request (A0), Thai QR, asking for the payload.',
      'Tag 05 = A3 (QR Thai STD), tag 06 = 02 ("request QR code data"), tag CN =',
      '  02 (C-scan-B: the guest scans a code we draw).',
      'CN is one of the six tags spelled with two ASCII characters rather than a',
      '  binary octet - 0x43 0x4E. §4.1.1’s generic BER rule does not describe',
      '  this tag set.',
      ...digioCitation,
    ],
    body: hexOf(digioQr.sent[0]),
  });
  out.push({
    file: 'digio/qr-payload-a18.hex',
    header: [
      'Digio - QR code data response (A18), the FIRST of two answers.',
      'Tags from the §"Response QR Code Data" block. The payload is on tag QR -',
      '  0x51 0x52 - with a BER long-form length, which is exactly the shape a',
      '  strict BER reader mis-reads (0x51 as a tag, 0x52 as a length).',
      'The payload here is a SIMULATED string, not an EMVCo code: the simulator',
      '  is not a PromptPay issuer and will not pretend to mint a payable one.',
      '  The real payload arrives on this same tag.',
      ...digioCitation,
    ],
    body: hexOf(digioQr.received[0]),
  });
  out.push({
    file: 'digio/sale-response-qr-approved.hex',
    header: [
      'Digio - QR sale response (A3), the SECOND answer, when the guest has paid.',
      'Tags from §5.4.2.3. TID on tag 16, MID on tag 17.',
      'Two responses to one request is why the adapter keeps reading after the',
      '  first complete frame and dispatches on tag 21.',
      ...digioCitation,
    ],
    body: hexOf(digioQr.received[1]),
  });

  const digioVoid = await digioExchange(async (terminal) => {
    const sale = await terminal.sale({
      attemptId: 'fixture',
      amountSatang: 10050,
      tender: 'card',
    });
    return terminal.void({
      attemptId: 'fixture',
      tender: 'card',
      amountSatang: 10050,
      tranRef: sale.tranRef ?? '',
    });
  });
  out.push({
    file: 'digio/void-request.hex',
    header: [
      'Digio - VOID request (A10).',
      'Tags from §5.5.1: 21 A10, 03 POS user, 04 a FRESH six-digit reference, 05',
      '  the transaction id of the sale being voided, 06 the void password.',
      'THE PASSWORD IN THIS FIXTURE IS A PLACEHOLDER WITH NO DIGITS IN IT. The',
      '  specification prints a fixed one; a credential in a vendor document is',
      '  still a credential, and the real one is configuration on the box.',
      ...digioCitation,
    ],
    body: hexOf(digioVoid.sent[1]),
  });
  out.push({
    file: 'digio/void-response.hex',
    header: [
      'Digio - VOID response (A11), approved.',
      'Tags from §5.5.2.1. Response code 100.',
      ...digioCitation,
    ],
    body: hexOf(digioVoid.received[1]),
  });

  const digioInquiry = await digioExchange((terminal) =>
    terminal.inquire({
      attemptId: 'fixture',
      tender: 'card',
      terminalRef: '010001',
      tranRef: 'NOSUCHTRANSACTIONIDXXXXX',
    }),
  );
  out.push({
    file: 'digio/inquiry-request.hex',
    header: [
      'Digio - INQUIRY request (T2).',
      'Tags from §5.13.1: 21 T2, 03 POS user, 04 a FRESH reference, 05 the',
      '  transaction being asked about.',
      'This is the only inquiry either vendor gives us, and it is Digio-only.',
      ...digioCitation,
    ],
    body: hexOf(digioInquiry.sent[0]),
  });
  out.push({
    file: 'digio/inquiry-not-found.hex',
    header: [
      'Digio - INQUIRY response (T3), transaction not found.',
      'Tags from §5.13.2: 21 T3, 22 = 203 "Transaction not found", 04 echoed.',
      'Found instead, the terminal answers with the SALE response (A1, A3, ...)',
      '  carrying the same transaction id and approval code as the answer that',
      '  was lost - which is what lets the cloud settle the attempt it has',
      '  instead of charging the guest again.',
      ...digioCitation,
    ],
    body: hexOf(digioInquiry.received[0]),
  });

  const digioHealth = await digioExchange((terminal) => terminal.health());
  out.push({
    file: 'digio/terminal-info-request.hex',
    header: [
      'Digio - TERMINAL INFO request (T0), the health probe.',
      'Tags from §5.1.1. "POS can send request the terminal info for test connect',
      '  edc device" - the only message in the dialect with no financial effect,',
      '  which is what a health probe has to be.',
      'The reference is alphabetic so it can never be one the counter minted.',
      ...digioCitation,
    ],
    body: hexOf(digioHealth.sent[0]),
  });
  out.push({
    file: 'digio/terminal-info-response.hex',
    header: [
      'Digio - TERMINAL INFO response (T1).',
      'Tags from §5.1.2: 22 response code, 04 reference, 05 versionCode, 06',
      '  serialNo. On THIS action tag 05 is a version string, while on every sale',
      '  response it is the transaction id.',
      ...digioCitation,
    ],
    body: hexOf(digioHealth.received[0]),
  });

  return out;
}

/** The file's whole text: header lines commented, a blank line, then the payload. */
export function renderFixture(fixture: Fixture): string {
  return `${fixture.header.map((line) => `# ${line}`.trimEnd()).join('\n')}\n\n${fixture.body}\n`;
}

/** The payload of a fixture file, with its header stripped. */
export function payloadOf(text: string): string {
  return text
    .split(/\r?\n/)
    .filter((line) => !line.startsWith('#'))
    .join('\n')
    .trim();
}

export const FIXTURE_DIR = path.dirname(fileURLToPath(import.meta.url));

async function main(): Promise<void> {
  for (const fixture of await buildFixtures()) {
    const target = path.join(FIXTURE_DIR, fixture.file);
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, renderFixture(fixture), 'utf8');
    process.stdout.write(`${fixture.file}\n`);
  }
}

if (process.argv.includes('--write')) await main();
