/**
 * Digio Direct Terminal BER-TLV — the PAX A920Pro (S2-10a).
 *
 * Source: "A920 Link-PoS-Spec" v2.21 (20 Oct 2025), read from
 * `imports/_vendor-docs/`. Section numbers below are that document's own.
 * Nothing of it is copied into the repository; what is here is the wire format
 * it describes, and the fixtures beside the tests are generated by this file
 * and checked against the three frames in the document that are trustworthy.
 *
 * FIVE FACTS THAT DECIDE EVERY LINE OF THIS FILE:
 *
 *  1. **The CRC is generated, never copied.** The rule is §4 — one byte, the
 *     XOR of every byte from the first header byte through the last content
 *     byte. Of the ten complete frames the document prints, SEVEN carry a CRC
 *     that rule does not produce (checked, with the alternatives — content
 *     only, length plus content, a byte sum — none of which reproduces them
 *     either; they are hand-edited examples). The §5.4.1 sale request is one of
 *     the three that are right, and reproducing it byte for byte is the proof
 *     that this generator is the one the terminal will agree with. That test is
 *     in `test/terminal-digio.test.ts` and it is the most important one here.
 *  2. **Tags are not generic BER.** §4.1.1 quotes the standard multi-octet rule
 *     and the actual tag set does not follow it: most tags are one binary octet
 *     (`21`, `01`, `0A`, `41`, `63`) but `QR`, `0M`, `CN` and `R1`-`R3` are two
 *     ASCII characters. `QR` is `0x51 0x52`, and `0x51 & 0x1F == 0x11`, so a
 *     strict BER reader takes `0x51` for a tag and `0x52` for a length and
 *     mis-reads the rest of the frame. The plant in the tests shows exactly
 *     that happening.
 *  3. **Tag numbers move between actions.** The TID is tag `13` on a credit
 *     response `A1` and tag `16` on a QR response `A3` — where `13` means Ref3.
 *     Tag `06` is the approval code on `A1`, the QR-code type on `A18`, the
 *     void password on `A10` and "do you want the QR payload" on the sale
 *     request. One shared "look up tag 13" helper is therefore a bug, and this
 *     file has a table per action instead.
 *  4. **Approved is `100`, three characters.** Not `00`. A success constant
 *     shared with the GHL adapter would get every Digio sale wrong.
 *  5. **A QR sale answers twice.** `A18` carries the payload in tag `QR` so our
 *     own display can draw it, and `A3` arrives when the guest has paid. The
 *     read loop keeps reading after the first complete frame and dispatches on
 *     tag `21`.
 *
 * One more, smaller: the per-row "TLV for Sample Value" column in the document
 * is systematically corrupt — it renders `A` as `0x4C`, sometimes fails to hex
 * the value at all, and sometimes prints the wrong tag byte. The Tag column and
 * the full-frame `Example:` lines are correct. Nothing here is derived from the
 * TLV column.
 */

import {
  TERMINAL_TIMEOUTS,
  TerminalError,
  last4Of,
  type FrameSpan,
  type PaymentTerminal,
  type TerminalChannel,
  type TerminalChannelFactory,
  type TerminalExchange,
  type TerminalHealth,
  type TerminalInquiryRequest,
  type TerminalOutcomeKind,
  type TerminalResult,
  type TerminalSaleRequest,
  type TerminalVoidRequest,
} from './contract';

const encoder = new TextEncoder();
const decoder = new TextDecoder('utf-8');

export const DIGIO_HEADER = Uint8Array.from([0x3e, 0x55]);

// --- Framing (§4) -----------------------------------------------------------

/** XOR of every byte given. The §4 rule, and the only CRC this file trusts. */
export function digioCrc(bytes: Uint8Array): number {
  let crc = 0;
  for (const byte of bytes) crc ^= byte;
  return crc;
}

/**
 * BER length (§4.1, the table at HTML lines 421-457).
 *
 * Short form to 127, then `81 nn`, `82 nn nn`, `83 nn nn nn`. The document's
 * row labels read `665535`/`665536` — a typo for 65535/65536 — but the
 * encodings it shows are correct BER, and every declared length in its ten
 * frame examples matches the content that follows it.
 */
export function encodeBerLength(length: number): Uint8Array {
  if (length < 0 || !Number.isInteger(length)) {
    throw new TerminalError('TERMINAL_BAD_REQUEST', `${length} is not a length`);
  }
  if (length <= 0x7f) return Uint8Array.from([length]);
  if (length <= 0xff) return Uint8Array.from([0x81, length]);
  if (length <= 0xffff) return Uint8Array.from([0x82, (length >> 8) & 0xff, length & 0xff]);
  if (length <= 0xffffff) {
    return Uint8Array.from([0x83, (length >> 16) & 0xff, (length >> 8) & 0xff, length & 0xff]);
  }
  throw new TerminalError('TERMINAL_BAD_REQUEST', `${length} bytes is more than one frame can say`);
}

export interface BerLength {
  value: number;
  /** How many bytes the length itself took. */
  width: number;
}

/** Read a BER length at `at`, or null when not enough has arrived yet. */
export function readBerLength(bytes: Uint8Array, at: number): BerLength | null {
  const first = bytes[at];
  if (first === undefined) return null;
  if (first <= 0x7f) return { value: first, width: 1 };
  const count = first & 0x7f;
  if (count === 0 || count > 3) {
    throw new TerminalError('TERMINAL_BAD_FRAME', `a BER length of ${count} octets is not one of ours`);
  }
  if (at + 1 + count > bytes.length) return null;
  let value = 0;
  for (let i = 0; i < count; i += 1) value = (value << 8) | (bytes[at + 1 + i] ?? 0);
  return { value, width: count + 1 };
}

/** `[3E 55][BER length][content][XOR CRC]`. */
export function encodeDigioFrame(content: Uint8Array): Uint8Array {
  const length = encodeBerLength(content.length);
  const frame = new Uint8Array(DIGIO_HEADER.length + length.length + content.length + 1);
  frame.set(DIGIO_HEADER, 0);
  frame.set(length, DIGIO_HEADER.length);
  frame.set(content, DIGIO_HEADER.length + length.length);
  // "CRC is ... calculated from the first byte of header to the last byte of
  // content" (§4). Everything but the CRC byte itself.
  frame[frame.length - 1] = digioCrc(frame.subarray(0, frame.length - 1));
  return frame;
}

/**
 * Take the content out of a frame, refusing one whose CRC does not check.
 *
 * REFUSING is the point. A byte flipped on a serial line is not rare, and the
 * alternative to refusing is reading an amount or a response code that is not
 * what the terminal sent. The caller turns the refusal into "we do not know
 * what happened", never into "declined".
 */
export function decodeDigioFrame(frame: Uint8Array): Uint8Array {
  if (frame.length < 4 || frame[0] !== DIGIO_HEADER[0] || frame[1] !== DIGIO_HEADER[1]) {
    throw new TerminalError('TERMINAL_BAD_FRAME', 'that is not a 3E55 frame');
  }
  const length = readBerLength(frame, 2);
  if (!length) throw new TerminalError('TERMINAL_BAD_FRAME', 'the frame ended inside its length');
  const start = 2 + length.width;
  const end = start + length.value;
  if (end + 1 !== frame.length) {
    throw new TerminalError(
      'TERMINAL_BAD_FRAME',
      `the frame says ${length.value} bytes of content and carries ${frame.length - start - 1}`,
    );
  }
  const expected = digioCrc(frame.subarray(0, end));
  const carried = frame[end];
  if (expected !== carried) {
    throw new TerminalError(
      'TERMINAL_BAD_FRAME',
      `the CRC is ${hex(carried ?? 0)} and the frame computes to ${hex(expected)}`,
    );
  }
  return frame.slice(start, end);
}

/** Find one whole `3E55` frame, dropping whatever came before it. */
export const digioFrameScanner = (buffered: Uint8Array): FrameSpan | null => {
  for (let start = 0; start + 1 < buffered.length; start += 1) {
    if (buffered[start] !== DIGIO_HEADER[0] || buffered[start + 1] !== DIGIO_HEADER[1]) continue;
    let length: BerLength | null;
    try {
      length = readBerLength(buffered, start + 2);
    } catch {
      // A length octet that is not ours: this `3E 55` was noise, not a header.
      continue;
    }
    if (!length) return null;
    const end = start + 2 + length.width + length.value + 1;
    if (end > buffered.length) return null;
    return { start, end };
  }
  return null;
};

function hex(byte: number): string {
  return byte.toString(16).padStart(2, '0').toUpperCase();
}

export function toHex(bytes: Uint8Array): string {
  return [...bytes].map(hex).join('');
}

export function fromHex(text: string): Uint8Array {
  const clean = text.replace(/\s+/g, '');
  if (clean.length % 2 !== 0) throw new Error('an odd number of hex digits');
  const out = new Uint8Array(clean.length / 2);
  for (let i = 0; i < out.length; i += 1) out[i] = Number.parseInt(clean.slice(i * 2, i * 2 + 2), 16);
  return out;
}

// --- Tags (§4.1.1, and the trap in it) --------------------------------------

/**
 * The tags spelled with two ASCII characters instead of one binary octet.
 *
 * Proven by the `A18` example frame, which literally contains `…QR 81 94 3030…`
 * (`0x51 0x52` then a BER long-form length). Everything else in the document's
 * tables is one octet, named by its hex spelling — which is why a tag is a
 * string here (`'21'`, `'0A'`, `'QR'`) rather than a number: the string is the
 * name the vendor's own tables use.
 */
export const DIGIO_NAMED_TAGS = ['QR', '0M', 'CN', 'R1', 'R2', 'R3'] as const;
const NAMED_FIRST_BYTES = new Set(DIGIO_NAMED_TAGS.map((tag) => tag.charCodeAt(0)));
const NAMED_SET = new Set<string>(DIGIO_NAMED_TAGS);

export interface DigioTlv {
  tag: string;
  value: string;
}

/** Turn a tag name into its bytes: `'21'` -> `[0x21]`, `'QR'` -> `[0x51,0x52]`. */
function tagBytes(tag: string): Uint8Array {
  if (NAMED_SET.has(tag)) return encoder.encode(tag);
  if (!/^[0-9A-F]{2}$/i.test(tag)) {
    throw new TerminalError('TERMINAL_BAD_REQUEST', `${tag} is not a tag this dialect has`);
  }
  return Uint8Array.from([Number.parseInt(tag, 16)]);
}

/** Build the content of a frame. Values are ASCII: every field is `a`/`an`/`ans`. */
export function encodeTlv(entries: readonly DigioTlv[]): Uint8Array {
  const chunks: Uint8Array[] = [];
  for (const entry of entries) {
    const value = encoder.encode(entry.value);
    chunks.push(tagBytes(entry.tag), encodeBerLength(value.length), value);
  }
  const total = chunks.reduce((sum, chunk) => sum + chunk.length, 0);
  const out = new Uint8Array(total);
  let at = 0;
  for (const chunk of chunks) {
    out.set(chunk, at);
    at += chunk.length;
  }
  return out;
}

/**
 * Read the content of a frame into tag/value pairs.
 *
 * The tokeniser knows the six named tags and nothing else about meaning —
 * interpretation is the per-action table's job, below. A tag byte that starts a
 * named tag but does not complete one falls back to being read as a single
 * octet rather than throwing: a firmware with a field we have not heard of must
 * not make the whole frame unreadable.
 */
export function readTlv(content: Uint8Array): DigioTlv[] {
  const out: DigioTlv[] = [];
  let at = 0;
  while (at < content.length) {
    const first = content[at] ?? 0;
    let tag: string;
    let tagWidth = 1;
    if (NAMED_FIRST_BYTES.has(first) && at + 1 < content.length) {
      const pair = String.fromCharCode(first, content[at + 1] ?? 0);
      if (NAMED_SET.has(pair)) {
        tag = pair;
        tagWidth = 2;
      } else tag = hex(first);
    } else tag = hex(first);
    const length = readBerLength(content, at + tagWidth);
    if (!length) {
      throw new TerminalError('TERMINAL_BAD_FRAME', `tag ${tag} has no length`);
    }
    const start = at + tagWidth + length.width;
    const end = start + length.value;
    if (end > content.length) {
      throw new TerminalError(
        'TERMINAL_BAD_FRAME',
        `tag ${tag} says ${length.value} bytes and the frame has ${content.length - start}`,
      );
    }
    out.push({ tag, value: decoder.decode(content.subarray(start, end)) });
    at = end;
  }
  return out;
}

/**
 * The same bytes read as generic BER, for the plant that shows why the table
 * above exists.
 *
 * Every tag is taken as one octet and every length as one octet, which is what
 * a reader written from §4.1.1 alone does. It is exported so the test can show
 * the mis-read rather than describe it, and it is called nowhere else.
 */
export function readTlvAsGenericBer(content: Uint8Array): DigioTlv[] {
  const out: DigioTlv[] = [];
  let at = 0;
  while (at + 1 < content.length) {
    const tag = hex(content[at] ?? 0);
    const length = content[at + 1] ?? 0;
    const start = at + 2;
    const end = Math.min(start + length, content.length);
    out.push({ tag, value: decoder.decode(content.subarray(start, end)) });
    at = end;
  }
  return out;
}

// --- Per-action tag tables (§5) ---------------------------------------------

/**
 * What each tag means, PER ACTION.
 *
 * Read the columns of §5.4.1, §5.4.2.1, §5.4.2.3, §5.5, §5.13 and §5.1 and the
 * moving tags jump out: `13` is the TID on `A1` and Ref3 on `A3`; `06` is four
 * different fields on four messages. The four that never move across the
 * response tables are `21` (action), `22` (response code), `04` (our reference)
 * and `01` (amount) — and those four are all an unknown action is read for.
 */
export const DIGIO_TAGS = {
  /** §5.4.1 Sale request. */
  A0: {
    '21': 'actionCode',
    '01': 'amount',
    '03': 'posUser',
    '04': 'ref',
    '05': 'paymentType',
    '06': 'requestQrData',
    '23': 'signOnPaper',
    '24': 'ref1',
    '25': 'ref2',
    '41': 'tipAmount',
    '63': 'field63',
    '0M': 'merchant',
    CN: 'channelType',
    R1: 'reserved1',
    R2: 'reserved2',
    R3: 'reserved3',
  },
  /** §5.4.2.1 Response Credit (A1). */
  A1: {
    '21': 'actionCode',
    '01': 'amount',
    '04': 'ref',
    '22': 'responseCode',
    '05': 'tranRef',
    '06': 'approvalCode',
    '07': 'cardType',
    '08': 'applicationLabel',
    '09': 'cardNo',
    '0A': 'cardHolderName',
    '0B': 'traceNo',
    '0D': 'aid',
    '0E': 'cvmType',
    '11': 'transDate',
    '12': 'transTime',
    '13': 'tid',
    '14': 'mid',
    '15': 'batchNo',
    '17': 'rrn',
    '18': 'tsi',
    '19': 'tvr',
    '20': 'entryType',
    '41': 'tipAmount',
  },
  /** §5.4.2.3 Response QR PromptPay (A3). Note `13` is Ref3 here, not the TID. */
  A3: {
    '21': 'actionCode',
    '04': 'ref',
    '22': 'responseCode',
    '01': 'amount',
    '05': 'tranRef',
    '10': 'qrReferenceCode',
    '11': 'ref1',
    '12': 'ref2',
    '13': 'ref3',
    '14': 'transDate',
    '15': 'transTime',
    '16': 'tid',
    '17': 'mid',
    '18': 'billerId',
    '20': 'bankCode',
  },
  /** §"Response QR Code Data" (A18) — the payload our own display draws. */
  A18: {
    '21': 'actionCode',
    '22': 'responseCode',
    '01': 'amount',
    '04': 'ref',
    '05': 'tranRef',
    '06': 'qrCodeType',
    '14': 'transDate',
    '15': 'transTime',
    '16': 'tid',
    '17': 'mid',
    QR: 'qrPayload',
  },
  /** §5.5.1 Void request. Tag `06` is the password and never leaves config. */
  A10: {
    '21': 'actionCode',
    '03': 'posUser',
    '04': 'ref',
    '05': 'tranRef',
    '06': 'password',
  },
  /** §5.5.2.1 Void response (A11 and its siblings). */
  A11: {
    '21': 'actionCode',
    '22': 'responseCode',
    '04': 'ref',
    '01': 'amount',
    '05': 'tranRef',
    '11': 'transDate',
    '12': 'transTime',
    '13': 'tid',
    '14': 'mid',
  },
  /** §5.1.1 Terminal Info request. */
  T0: { '21': 'actionCode', '04': 'ref' },
  /** §5.1.2 Terminal Info response — the health probe's answer. */
  T1: {
    '21': 'actionCode',
    '22': 'responseCode',
    '04': 'ref',
    '05': 'softwareVersion',
    '06': 'serialNumber',
  },
  /** §5.13.1 Inquiry request. */
  T2: { '21': 'actionCode', '03': 'posUser', '04': 'ref', '05': 'tranRef' },
  /** §5.13.2 Inquiry, transaction not found. */
  T3: { '21': 'actionCode', '22': 'responseCode', '04': 'ref' },
} as const satisfies Record<string, Record<string, string>>;

export type DigioAction = keyof typeof DIGIO_TAGS;

/** The four tags that mean the same thing on every response in the document. */
const DIGIO_STABLE_TAGS: Record<string, string> = {
  '21': 'actionCode',
  '22': 'responseCode',
  '04': 'ref',
  '01': 'amount',
};

export type DigioFields = Record<string, string>;

/**
 * Read a response's fields using the table for the action it declares.
 *
 * The action comes off tag `21` first and the table is chosen from it, which is
 * the whole discipline: nothing here asks "what is tag 13" without having
 * decided which message it is looking at. An action with no table is read for
 * the four stable tags and its other fields are kept under their tag names, so
 * a wallet response this ticket does not implement is still legible in a log.
 */
export function readDigioResponse(content: Uint8Array): {
  action: string;
  fields: DigioFields;
  known: boolean;
} {
  const entries = readTlv(content);
  const action = entries.find((entry) => entry.tag === '21')?.value ?? '';
  const table: Record<string, string> =
    (DIGIO_TAGS as Record<string, Record<string, string>>)[action] ?? DIGIO_STABLE_TAGS;
  const known = action in DIGIO_TAGS;
  const fields: DigioFields = {};
  for (const entry of entries) {
    fields[table[entry.tag] ?? `tag${entry.tag}`] = entry.value;
  }
  return { action, fields, known };
}

// --- Vocabulary (§6.1 action codes, §6.2 response codes) --------------------

export const DIGIO_RESPONSE = {
  CANCELLED: '000',
  BROKEN_PIPE: '001',
  INVALID_FORMAT: '002',
  INVALID_LENGTH: '003',
  SUCCESS: '100',
  MULTI_MERCHANT_UNSUPPORTED: '201',
  FUNCTION_UNSUPPORTED: '202',
  NOT_FOUND: '203',
  ALREADY_VOIDED: '204',
  ALREADY_SETTLED: '205',
  FINALIZE_REQUIRED: '306',
  /** Not in the §6.2 table: §5.5's prose gives it for a void of a type that has none. */
  VOID_UNSUPPORTED: '333',
  PROCESSING_ERROR: '400',
  HOST_TIMEOUT: '401',
  TERMINAL_NOT_READY: '500',
} as const;

const DIGIO_RESPONSE_TEXT: Record<string, string> = {
  '000': 'Transaction cancelled',
  '001': 'Broken pipe',
  '002': 'Invalid format',
  '003': 'Invalid data length',
  '100': 'Transaction Success',
  '201': 'Multiple Merchant is not support',
  '202': 'Function is not support',
  '203': 'Transaction not found',
  '204': 'Transaction already voided',
  '205': 'Transaction already settle',
  '306': 'Finalize required',
  '333': 'This transaction type cannot be voided',
  '400': 'Processing error',
  '401': 'Host timeout',
  '500': 'Terminal not ready',
};

export function digioResponseText(code: string | undefined | null): string {
  if (!code) return 'the terminal sent no response code';
  return DIGIO_RESPONSE_TEXT[code] ?? `Bank error (code ${code})`;
}

/**
 * Payment type for the sale request's tag `05`.
 *
 * "if you not set default will be select payment type screen" (§5.4.1) — which
 * is a member of staff choosing on the terminal instead of the till deciding,
 * so this is always sent.
 *
 * A4 IS WECHAT AND A5 IS ALIPAY. §6.1 and the tag-05 comment both say so; the
 * §5.4.2.4 heading says the opposite and its own body contradicts the heading.
 * Two against one, and Digio have been asked.
 */
export const DIGIO_PAYMENT_TYPES = {
  card: 'A1',
  qr: 'A3',
  wechat: 'A4',
  alipay: 'A5',
} as const;

/** `01` = we scan the guest's code, `02` = the guest scans ours (§5.4.1 tag CN). */
export const DIGIO_CHANNEL = { normal: '00', scan: '01', show: '02' } as const;

/** Six digits, and alphabetic so it can never be one the counter minted. */
export const DIGIO_PROBE_REF = 'PROBE0';

/** Satang as ASCII digits; 12 is the field's maximum (§5.4.1 tag `01`). */
export function digioAmount(satang: number): string {
  if (!Number.isInteger(satang) || satang < 0) {
    throw new TerminalError('TERMINAL_BAD_REQUEST', `${satang} is not an amount in satang`);
  }
  const text = String(satang);
  if (text.length > 12) {
    throw new TerminalError('TERMINAL_BAD_REQUEST', `${satang} is more than 12 digits`);
  }
  return text;
}

export function digioSatang(value: string | undefined | null): number | null {
  if (!value || !/^\d{1,12}$/.test(value.trim())) return null;
  return Number(value.trim());
}

// --- The adapter ------------------------------------------------------------

export interface DigioDeps {
  deviceId: string;
  label: string;
  /** From the device row, and usually null: the park's PAX units have no TID on file. */
  terminalId: string | null;
  merchantId: string | null;
  open: TerminalChannelFactory;
  /** Mint a fresh six-digit reference. Sales, voids and inquiries all draw on it. */
  nextRef: () => Promise<string>;
  now: () => Date;
  cashier?: string | null;
  /**
   * The void password, from CONFIGURATION.
   *
   * The vendor prints a fixed one in §5.5 and that does not make it ours to
   * write down: a credential in a vendor document is still a credential, so it
   * reaches the box as an environment value and a void with none configured is
   * refused here rather than sent with a guess. It is never logged, never put
   * in an `ops_run` and never in a fixture.
   */
  voidPassword?: string | null;
  /**
   * The read deadlines, overridable.
   *
   * `TERMINAL_TIMEOUTS` is the park's, and a test that wanted to prove the
   * "no final answer" branch against the real budget would sit for two minutes
   * doing nothing — so the budget is a dependency, exactly as the print queue's
   * retry delay is. Nothing in production passes one.
   */
  timeouts?: { saleMs?: number; probeMs?: number };
}

/** A response that is not the end of the conversation. */
function isInterim(action: string, responseCode: string | undefined): boolean {
  /**
   * `A18` is the QR payload, sent before the guest has paid. `306` is the
   * terminal asking for a QR reference code, which §5.4.2.3 says arrives before
   * the real response. Both mean: keep reading.
   */
  return action === 'A18' || responseCode === DIGIO_RESPONSE.FINALIZE_REQUIRED;
}

export function digioTerminal(deps: DigioDeps): PaymentTerminal {
  const { deviceId, label } = deps;
  const saleMs = deps.timeouts?.saleMs ?? TERMINAL_TIMEOUTS.customerInteractionMs;
  const probeMs = deps.timeouts?.probeMs ?? TERMINAL_TIMEOUTS.probeMs;

  async function withChannel<T>(fn: (channel: TerminalChannel) => Promise<T>): Promise<T> {
    const channel = await deps.open();
    try {
      return await fn(channel);
    } finally {
      await channel.close().catch(() => {});
    }
  }

  function blank(
    attemptId: string,
    requestedSatang: number,
    outcome: TerminalOutcomeKind,
    text: string,
    startedAt: number,
    extra: Partial<TerminalResult> = {},
  ): TerminalResult {
    return {
      attemptId,
      deviceId,
      protocol: 'digio_tlv',
      outcome,
      requestedSatang,
      approvedSatang: null,
      terminalRef: null,
      tranRef: null,
      invoiceNo: null,
      approvalCode: null,
      last4: null,
      tid: deps.terminalId,
      mid: deps.merchantId,
      qrPayload: null,
      responseCode: null,
      responseText: text,
      elapsedMs: Date.now() - startedAt,
      at: deps.now().toISOString(),
      ...extra,
    };
  }

  function paymentTypeFor(tender: TerminalSaleRequest['tender'], wallet?: string | null): string {
    if (tender === 'card') return DIGIO_PAYMENT_TYPES.card;
    const named = wallet?.trim().toUpperCase() ?? '';
    if (named.includes('WECHAT')) return DIGIO_PAYMENT_TYPES.wechat;
    if (named.includes('ALIPAY')) return DIGIO_PAYMENT_TYPES.alipay;
    return DIGIO_PAYMENT_TYPES.qr;
  }

  /** Turn one parsed response into a result. */
  function resultOf(
    request: { attemptId: string; amountSatang: number },
    /** Which exchange asked. The amount rule below is a sale's alone. */
    exchange: TerminalExchange,
    ref: string,
    parsed: { action: string; fields: DigioFields },
    qrPayload: string | null,
    startedAt: number,
  ): TerminalResult {
    const { fields } = parsed;
    const code = fields.responseCode ?? null;
    const approvedSatang = digioSatang(fields.amount);
    let outcome: TerminalOutcomeKind;
    switch (code) {
      case DIGIO_RESPONSE.SUCCESS:
        outcome = 'approved';
        break;
      case DIGIO_RESPONSE.CANCELLED:
        outcome = 'cancelled';
        break;
      case DIGIO_RESPONSE.NOT_FOUND:
        outcome = 'not_found';
        break;
      case DIGIO_RESPONSE.HOST_TIMEOUT:
        // The terminal is alive and its host is not. Money may have moved.
        outcome = 'timeout';
        break;
      case DIGIO_RESPONSE.VOID_UNSUPPORTED:
      case DIGIO_RESPONSE.FUNCTION_UNSUPPORTED:
        outcome = 'unsupported';
        break;
      case null:
        outcome = 'no_response';
        break;
      default:
        outcome = 'declined';
    }
    if (
      exchange === 'sale' &&
      outcome === 'approved' &&
      approvedSatang !== null &&
      approvedSatang !== request.amountSatang
    ) {
      /**
       * Digio has no partial-approval code, which does not mean a partial
       * approval cannot reach us — it means the only evidence of one is the
       * amount. Same branch as GHL's `10`: refuse the sale and void the tender.
       *
       * And a sale's evidence only. A `T2` inquiry is answered with the SALE
       * response (§5.13.2), and an `A11` void answers with the amount it gave
       * back — after a partial approval that is the approved amount, which is
       * not what the sale asked for. Measuring either against the request
       * would make the void that undoes a partial approval read as another
       * partial approval, and the caller would void a void.
       */
      outcome = 'partial_approval';
    }
    return {
      attemptId: request.attemptId,
      deviceId,
      protocol: 'digio_tlv',
      outcome,
      requestedSatang: request.amountSatang,
      approvedSatang,
      terminalRef: fields.ref ?? ref,
      tranRef: fields.tranRef ?? null,
      invoiceNo: null,
      approvalCode: fields.approvalCode ?? null,
      /** The masked PAN is read and thrown away; only the last four survive. */
      last4: last4Of(fields.cardNo),
      /**
       * Straight off the wire where the wire has it — and worth writing back
       * onto the device row, because neither PAX in the park has a TID or MID
       * on file (`DEVICE_INVENTORY.md:40-41`).
       */
      tid: fields.tid ?? deps.terminalId,
      mid: fields.mid ?? deps.merchantId,
      qrPayload,
      responseCode: code,
      responseText: digioResponseText(code),
      elapsedMs: Date.now() - startedAt,
      at: deps.now().toISOString(),
    };
  }

  /**
   * Read frames until a final one, or until the budget runs out.
   *
   * This loop is the two-response QR exchange: an `A18` hands the payload
   * straight to the caller so the display can draw it, and the read continues
   * for the `A3` that says the guest has paid.
   */
  async function readUntilFinal(
    channel: TerminalChannel,
    exchange: TerminalExchange,
    request: { attemptId: string; amountSatang: number },
    ref: string,
    budgetMs: number,
    startedAt: number,
    onProgress?: TerminalSaleRequest['onProgress'],
  ): Promise<TerminalResult> {
    let qrPayload: string | null = null;
    const deadline = Date.now() + budgetMs;
    for (;;) {
      const left = deadline - Date.now();
      if (left <= 0) {
        return blank(
          request.attemptId,
          request.amountSatang,
          'no_response',
          'the terminal gave no final answer inside the customer-interaction budget',
          startedAt,
          { terminalRef: ref, qrPayload },
        );
      }
      const frame = await channel.readFrame(digioFrameScanner, left);
      if (!frame) {
        return blank(
          request.attemptId,
          request.amountSatang,
          'no_response',
          'the terminal gave no final answer inside the customer-interaction budget',
          startedAt,
          { terminalRef: ref, qrPayload },
        );
      }
      let parsed: { action: string; fields: DigioFields };
      try {
        parsed = readDigioResponse(decodeDigioFrame(frame));
      } catch (err) {
        /**
         * A frame that will not read is not a decline.
         *
         * A bad CRC means one of the bytes is wrong and we cannot say which —
         * the amount, the response code, the transaction id. Whether the money
         * moved is unknown, and `no_response` is the outcome that says so and
         * sends the till to the inquiry rule.
         */
        return blank(
          request.attemptId,
          request.amountSatang,
          'no_response',
          `the terminal's answer could not be read: ${err instanceof Error ? err.message : String(err)}`,
          startedAt,
          { terminalRef: ref, qrPayload },
        );
      }
      if (parsed.action === 'A18') {
        qrPayload = parsed.fields.qrPayload ?? qrPayload;
        if (qrPayload) {
          onProgress?.({
            kind: 'qr_payload',
            attemptId: request.attemptId,
            deviceId,
            qrPayload,
            tranRef: parsed.fields.tranRef ?? null,
            at: deps.now().toISOString(),
          });
        }
      }
      if (isInterim(parsed.action, parsed.fields.responseCode)) continue;
      return resultOf(request, exchange, ref, parsed, qrPayload, startedAt);
    }
  }

  return {
    deviceId,
    label,
    protocol: 'digio_tlv',

    async sale(request) {
      const startedAt = Date.now();
      const ref = await deps.nextRef();
      const entries: DigioTlv[] = [
        { tag: '21', value: 'A0' },
        { tag: '01', value: digioAmount(request.amountSatang) },
        // Tag `03` is mandatory on every request. `POS` is what a till with no
        // named operator is, and it is a stamp on the terminal's own slip.
        { tag: '03', value: request.cashier ?? deps.cashier ?? 'POS' },
        { tag: '04', value: ref },
        { tag: '05', value: paymentTypeFor(request.tender, request.wallet) },
      ];
      if (request.requestQrPayload) entries.push({ tag: '06', value: '02' });
      if (request.tender !== 'card') {
        entries.push({
          tag: 'CN',
          value: request.qrDirection === 'scan' ? DIGIO_CHANNEL.scan : DIGIO_CHANNEL.show,
        });
      }
      const frame = encodeDigioFrame(encodeTlv(entries));
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(frame);
        request.onProgress?.({
          kind: 'sent',
          attemptId: request.attemptId,
          deviceId,
          at: deps.now().toISOString(),
        });
        return readUntilFinal(
          channel,
          'sale',
          request,
          ref,
          saleMs,
          startedAt,
          request.onProgress,
        );
      });
    },

    async inquire(request: TerminalInquiryRequest) {
      const startedAt = Date.now();
      /**
       * A FRESH reference, unlike GHL's QUERY.
       *
       * Tag `04` is "unique reference number from 3rd party" on every message
       * including this one, and the transaction being asked about is named by
       * tag `05` instead. This is the only inquiry either vendor gives us.
       */
      const ref = await deps.nextRef();
      const entries: DigioTlv[] = [
        { tag: '21', value: 'T2' },
        { tag: '03', value: request.cashier ?? deps.cashier ?? 'POS' },
        { tag: '04', value: ref },
      ];
      if (request.tranRef) entries.push({ tag: '05', value: request.tranRef });
      const frame = encodeDigioFrame(encodeTlv(entries));
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(frame);
        /**
         * The answer to a `T2` is a SALE response when the transaction is
         * found — `A1`, `A3` and so on, §5.13.2 — and a `T3` with `203` when it
         * is not. So an approved inquiry carries the same transaction id and
         * approval code as the answer that was lost, which is what lets the
         * cloud settle the existing attempt instead of charging again.
         */
        return readUntilFinal(
          channel,
          'inquire',
          { attemptId: request.attemptId, amountSatang: request.amountSatang ?? 0 },
          ref,
          probeMs,
          startedAt,
        );
      });
    },

    async void(request: TerminalVoidRequest) {
      const startedAt = Date.now();
      if (!deps.voidPassword) {
        throw new TerminalError(
          'TERMINAL_NOT_CONFIGURED',
          'this box has no void password configured for its Digio terminals',
        );
      }
      const ref = await deps.nextRef();
      const frame = encodeDigioFrame(
        encodeTlv([
          { tag: '21', value: 'A10' },
          { tag: '03', value: request.cashier ?? deps.cashier ?? 'POS' },
          { tag: '04', value: ref },
          { tag: '05', value: request.tranRef },
          { tag: '06', value: deps.voidPassword },
        ]),
      );
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(frame);
        const result = await readUntilFinal(
          channel,
          'void',
          request,
          ref,
          probeMs,
          startedAt,
        );
        /**
         * "Transaction already voided" is the end state a void wants. Reporting
         * it as a decline would make a second, harmless void look like a
         * failure and could send somebody looking for money that is already
         * back with the guest.
         */
        if (result.responseCode === DIGIO_RESPONSE.ALREADY_VOIDED) {
          return { ...result, outcome: 'approved' as const };
        }
        return result;
      });
    },

    async settle() {
      // No verified transaction-level settlement wire contract is supplied.
      // Digio section 5.12 uses non-BER tags SA..SP; GHL specifies no settle.
      return { outcome: 'unsupported' as const, deviceId: deps.deviceId,
        errorCode: 'TERMINAL_SETTLEMENT_UNSUPPORTED', lines: [] };
    },
    async health() {
      const checkedAt = deps.now().toISOString();
      const frame = encodeDigioFrame(
        encodeTlv([
          { tag: '21', value: 'T0' },
          { tag: '04', value: DIGIO_PROBE_REF },
        ]),
      );
      try {
        return await withChannel(async (channel) => {
          channel.discard();
          await channel.write(frame);
          const answer = await channel.readFrame(digioFrameScanner, probeMs);
          if (!answer) {
            return {
              reachability: 'unreachable' as const,
              serialNumber: null,
              softwareVersion: null,
              tid: deps.terminalId,
              mid: deps.merchantId,
              lastError: 'the terminal answered nothing',
              checkedAt,
            };
          }
          const parsed = readDigioResponse(decodeDigioFrame(answer));
          return {
            /**
             * `T0`/`T1` is the vendor's own "test connect edc device" (§5.1)
             * and the only message in the dialect with no financial effect,
             * which is exactly what a health probe has to be.
             */
            reachability: 'reachable' as const,
            serialNumber: parsed.fields.serialNumber ?? null,
            softwareVersion: parsed.fields.softwareVersion ?? null,
            tid: parsed.fields.tid ?? deps.terminalId,
            mid: parsed.fields.mid ?? deps.merchantId,
            lastError:
              parsed.fields.responseCode === DIGIO_RESPONSE.SUCCESS
                ? null
                : digioResponseText(parsed.fields.responseCode),
            checkedAt,
          };
        });
      } catch (err) {
        return {
          reachability: 'unreachable' as const,
          serialNumber: null,
          softwareVersion: null,
          tid: deps.terminalId,
          mid: deps.merchantId,
          lastError: err instanceof TerminalError ? err.code : 'TERMINAL_UNREACHABLE',
          checkedAt,
        } satisfies TerminalHealth;
      }
    },
  };
}
