/**
 * GHL LinkPOS XML — the NEXGO N5 on the SCB acquirer (S2-10a).
 *
 * Source: "SMART POS API — Integration POS to SmartEDC for Siam Commercial Bank
 * PCL" v1.4 (Jan 2025), read from `imports/_vendor-docs/`. Page references
 * below are that document's own pages. Nothing of it is copied into the
 * repository; what is here is the wire format it describes.
 *
 * FIVE FACTS THAT DECIDE EVERY LINE OF THIS FILE, each of which a reasonable
 * implementation gets wrong if it works from the parameter tables alone:
 *
 *  1. **There is no framing.** No length, no STX/ETX, no checksum, no ACK. The
 *     vendor's own sample writes the XML string straight at the port and reads
 *     with `ReadExisting()` (p.18). So a message ends at `</xml>` and anything
 *     before `<xml>` is noise to be dropped.
 *  2. **Two disjoint response-code spaces share one field.** A card SALE
 *     answers ISO-8583 style from the SCB host — `00` approved, `10` partial
 *     approval, `05` do not honor (pp.8-10). A wallet SALE, every QUERY and
 *     every VOID answer `00` SUCCESS / `01` FAILED, generated by the SmartEDC
 *     itself (pp.11, 13, 16, 17). Read `response_code` without first looking at
 *     `trade_type` and a declined card reads as a successful one.
 *  3. **`pos_ref_no` is 12 characters.** The document says String(20) on SALE,
 *     String(12) on QUERY and String(32) on VOID (pp.8, 13, 16-17). Twelve is
 *     the intersection and fits all three fields.
 *  4. **There is no QUERY for CARD** (p.13, in the vendor's own words). A card
 *     sale that gets no final response cannot be chased on this dialect at all,
 *     which is why the audited staff-confirmation dialog is the permanent path
 *     for a NEXGO card and not a degraded one.
 *  5. **A void is keyed on `invoice_no`** (plus `card_approval_code` for a
 *     card), and its `pos_ref_no` is a FRESH reference for the void itself
 *     (pp.16-17). Reusing the sale's reference breaks the uniqueness the vendor
 *     requires of it.
 *
 * WHAT THE DOCUMENT DOES NOT CONTAIN. Page 18 is the only literal message in
 * it, it is a REQUEST builder, and there is no response XML anywhere. Element
 * names, types and requiredness are cited from the parameter tables and are
 * solid; the `<xml>` wrapper and the ordering of responses are reconstructed
 * from the sample's convention. Every response fixture in
 * `test/fixtures/terminal/ghl/` says so in its header, and one real captured
 * exchange is wanted before this adapter is called verified against hardware.
 */

import {
  TERMINAL_TIMEOUTS,
  TerminalError,
  last4Of,
  type FrameSpan,
  type PaymentTerminal,
  type TerminalChannel,
  type TerminalChannelFactory,
  type TerminalHealth,
  type TerminalInquiryRequest,
  type TerminalOutcomeKind,
  type TerminalResult,
  type TerminalSaleRequest,
  type TerminalVoidRequest,
} from './contract';

const encoder = new TextEncoder();
const decoder = new TextDecoder('utf-8');

/**
 * The element order on the wire, from the only literal message in the document
 * (p.18).
 *
 * It is NOT the order of any parameter table, and it carries an element —
 * `cashier` — that appears in no table at all. The sample sends every element
 * on every message, empty for the ones the operation does not use, so this
 * encoder does the same: a terminal that ignores an empty element is a terminal
 * behaving as its own vendor's sample assumes.
 */
export const GHL_REQUEST_ORDER = [
  'trade_type',
  'pos_ref_no',
  'amount',
  'invoice_no',
  'transaction_id',
  'transaction_type',
  'service_type',
  /**
   * RECONSTRUCTED. The card VOID requires `card_approval_code` (p.16) and the
   * sample has no slot for it, so it goes here — after the last element the
   * sample names and before `cashier`, which is the operator stamp and reads
   * last in every message the vendor prints.
   */
  'card_approval_code',
  'cashier',
] as const;
export type GhlElement = (typeof GHL_REQUEST_ORDER)[number];

/**
 * A response's elements, and this order is RECONSTRUCTED.
 *
 * The document prints no response XML at all, so what is cited here is the
 * parameter tables: p.8 names seven fields for a card sale and this order is
 * p.8's when only those seven are present; p.11 names six for a wallet; p.13-14
 * names ten for a QUERY, including the only place this dialect ever sends a TID
 * or a MID. A response carries the fields its table names and NOT the request's
 * nine — a terminal does not echo an empty `<cashier>` back — which is why this
 * is a separate list rather than the same one with blanks.
 *
 * The parser is order-independent, so nothing depends on this being right; it
 * exists so the fixtures look like what a terminal would send rather than like
 * something generated.
 */
export const GHL_RESPONSE_ORDER = [
  'pos_ref_no',
  'transaction_type',
  'trade_type',
  'response_code',
  'response_msg',
  'invoice_no',
  'transaction_id',
  'card_no',
  'amount',
  'card_approval_code',
  'terminal_id',
  'merchant_id',
] as const;

export type GhlFields = Partial<Record<string, string>>;

/** `CARD`, and the wallets the document lists (p.11). */
export const GHL_CARD_TRADE_TYPE = 'CARD';
export const GHL_WALLET_TRADE_TYPES = [
  'ALIPAY',
  'ALIPAY+',
  'WECHATPAY',
  'TRUEMONEY',
  'DOLFIN',
  'QRCS',
  'THAIQRCODE',
] as const;

/** `SCAN` is we read the guest's code; `SHOWQR` is the guest reads ours (p.11). */
export const GHL_SERVICE_TYPES = ['SCAN', 'SHOWQR'] as const;

/**
 * Visa/Master QR cannot do B-scan-C.
 *
 * Decoded from the support matrix on p.12, whose cells are 2×2-pixel images
 * rather than text: `QRCS` is the one red cell in the Scan column. Marked as
 * decoded because it is an inference from cell fills, and enforced anyway —
 * enforcing it is the only way the adapter's validation is ever exercised.
 */
export const GHL_SHOWQR_ONLY: readonly string[] = ['QRCS'];

/** 12 characters: the intersection of the document's 20, 12 and 32 (p.8/13/16). */
export const GHL_POS_REF_MAX = 12;

/**
 * A probe reference, for the health check this dialect does not document.
 *
 * Deliberately alphanumeric so it can never be a reference the counter minted —
 * those are twelve digits — and so a QUERY that carries it cannot be mistaken
 * for a real transaction lookup by anybody reading a terminal's log.
 */
export const GHL_PROBE_REF = 'HEALTHPROBE0';

const XML_OPEN = encoder.encode('<xml>');
const XML_CLOSE = encoder.encode('</xml>');

/** Find `<xml>…</xml>`, dropping whatever came before it. */
export const ghlFrameScanner = (buffered: Uint8Array): FrameSpan | null => {
  const start = indexOfBytes(buffered, XML_OPEN, 0);
  if (start < 0) return null;
  const close = indexOfBytes(buffered, XML_CLOSE, start);
  if (close < 0) return null;
  return { start, end: close + XML_CLOSE.length };
};

function indexOfBytes(haystack: Uint8Array, needle: Uint8Array, from: number): number {
  outer: for (let i = from; i + needle.length <= haystack.length; i += 1) {
    for (let k = 0; k < needle.length; k += 1) {
      if (haystack[i + k] !== needle[k]) continue outer;
    }
    return i;
  }
  return -1;
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function unescapeXml(value: string): string {
  return value
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'")
    .replace(/&amp;/g, '&');
}

/**
 * Build one request, in the sample's element order.
 *
 * Every element every time, empty for the ones this operation does not use,
 * because that is what the vendor's own sample does (p.18) — a terminal that
 * ignores an empty element is a terminal behaving as its vendor assumes.
 */
export function encodeGhlRequest(fields: GhlFields): string {
  const parts = GHL_REQUEST_ORDER.map(
    (name) => `<${name}>${escapeXml(fields[name] ?? '')}</${name}>`,
  );
  return `<xml>${parts.join('')}</xml>`;
}

/** Build one response: the fields its table names, and no others. */
export function encodeGhlResponse(fields: GhlFields): string {
  const named = new Set<string>(GHL_RESPONSE_ORDER);
  const ordered = GHL_RESPONSE_ORDER.filter((name) => fields[name] !== undefined);
  const extra = Object.keys(fields).filter((name) => !named.has(name));
  const parts = [...ordered, ...extra].map(
    (name) => `<${name}>${escapeXml(fields[name] ?? '')}</${name}>`,
  );
  return `<xml>${parts.join('')}</xml>`;
}

/**
 * Read one message, order-independently.
 *
 * Order-independent because the sample proves only what a REQUEST looks like
 * and the responses are reconstructed: an adapter that insisted on an order
 * nobody documented would break on the first real terminal that answered in a
 * different one. Unknown elements are kept rather than dropped, so a firmware
 * that adds a field shows up in a log line instead of vanishing.
 */
export function parseGhl(xml: string): GhlFields {
  const body = xml.slice(xml.indexOf('<xml>') + 5, xml.lastIndexOf('</xml>'));
  const out: GhlFields = {};
  const element = /<([a-z_][a-z0-9_]*)>([\s\S]*?)<\/\1>/gi;
  for (;;) {
    const match = element.exec(body);
    if (!match) break;
    out[match[1] as string] = unescapeXml((match[2] ?? '').trim());
  }
  return out;
}

// --- Amounts ----------------------------------------------------------------

/**
 * Satang to the decimal major units this dialect sends: `10025` -> `100.25`.
 *
 * Two decimals, a full stop, no separators and no symbol (p.8, p.11, p.16).
 */
export function ghlAmount(satang: number): string {
  if (!Number.isInteger(satang) || satang < 0) {
    throw new TerminalError('TERMINAL_BAD_REQUEST', `${satang} is not an amount in satang`);
  }
  return `${Math.floor(satang / 100)}.${String(satang % 100).padStart(2, '0')}`;
}

/**
 * Back the other way, by STRING rather than by float.
 *
 * `parseFloat('100.25') * 100` is 10025.000000000002 and rounds correctly
 * today; it is one refactor away from not doing. The comparison this feeds —
 * approved amount against requested amount — is the one that decides whether a
 * guest is charged the wrong sum, so it is done on integers derived by cutting
 * the string, and an amount that does not look like an amount is refused.
 */
export function ghlSatang(amount: string | undefined | null): number | null {
  if (!amount) return null;
  const match = /^(\d+)(?:\.(\d{1,2}))?$/.exec(amount.trim());
  if (!match) return null;
  const minor = (match[2] ?? '').padEnd(2, '0');
  return Number(match[1]) * 100 + Number(minor);
}

// --- Response codes ---------------------------------------------------------

/**
 * Which of the two code spaces a message is answered in.
 *
 * The whole of fact 2 in the file header, in one function, so that no branch
 * anywhere else has to remember it.
 */
export function ghlCodeSpace(tradeType: string, transactionType: string): 'iso' | 'status' {
  return tradeType.toUpperCase() === GHL_CARD_TRADE_TYPE && transactionType.toUpperCase() === 'SALE'
    ? 'iso'
    : 'status';
}

/**
 * The ISO codes from pp.8-10, as far as the document names them.
 *
 * Printed without leading zeros in the table but typed String(2) with examples
 * `00, 01, 02, …`, so everything here is compared zero-padded. Only the codes
 * with a meaning this adapter acts on are spelled out; the rest are declines
 * with their number, which is what a person at a till needs and all the
 * document gives.
 */
const GHL_ISO_TEXT: Record<string, string> = {
  '00': 'Approved',
  '01': 'Refer to card issuer',
  '02': 'Refer to card issuer, special condition',
  '03': 'Invalid merchant or service provider',
  '04': 'Pickup',
  '05': 'Do not honor',
  '06': 'General error',
  '07': 'Pickup card, special condition',
  '08': 'Honor with identification',
  '09': 'Request in progress',
  '10': 'Partial approval',
  '11': 'VIP approval',
};

export const GHL_ISO_APPROVED = '00';
export const GHL_ISO_PARTIAL = '10';
/** `09` Request in progress: the host has not finished. Money may yet move. */
export const GHL_ISO_IN_PROGRESS = '09';
export const GHL_STATUS_SUCCESS = '00';
export const GHL_STATUS_FAILED = '01';

/** Zero-pad a code the table printed without its leading zero. */
export function ghlCode(raw: string | undefined | null): string | null {
  const trimmed = raw?.trim();
  if (!trimmed) return null;
  return trimmed.length === 1 ? `0${trimmed}` : trimmed;
}

export interface GhlVerdict {
  outcome: TerminalOutcomeKind;
  text: string;
}

/** Turn a code into an outcome, in the space its trade type answers in. */
export function interpretGhl(
  tradeType: string,
  transactionType: string,
  rawCode: string | undefined | null,
  responseMsg?: string | null,
): GhlVerdict {
  const code = ghlCode(rawCode);
  if (!code) return { outcome: 'no_response', text: 'the terminal sent no response code' };
  if (ghlCodeSpace(tradeType, transactionType) === 'iso') {
    if (code === GHL_ISO_APPROVED) return { outcome: 'approved', text: GHL_ISO_TEXT['00'] as string };
    if (code === GHL_ISO_PARTIAL) {
      return { outcome: 'partial_approval', text: GHL_ISO_TEXT['10'] as string };
    }
    if (code === GHL_ISO_IN_PROGRESS) {
      /**
       * Not a decline. The host is still working, so whether money moved is
       * unknown — the one answer that must never be turned into "no", because
       * a till that offered the card again would charge the guest twice.
       */
      return { outcome: 'timeout', text: GHL_ISO_TEXT['09'] as string };
    }
    return { outcome: 'declined', text: GHL_ISO_TEXT[code] ?? `Declined (code ${code})` };
  }
  if (code === GHL_STATUS_SUCCESS) return { outcome: 'approved', text: responseMsg || 'SUCCESS' };
  if (code === GHL_STATUS_FAILED) return { outcome: 'declined', text: responseMsg || 'FAIL' };
  return { outcome: 'declined', text: responseMsg || `Unknown response code ${code}` };
}

// --- The adapter ------------------------------------------------------------

export interface GhlDeps {
  deviceId: string;
  label: string;
  /**
   * TID and MID off the device row, because they are NOT on the card wire.
   *
   * The card SALE response is seven fields and neither is among them (p.8);
   * they reach us only through a QUERY, which exists only for non-card. So for
   * every card tender these are the device row's, and the device row is the
   * Console's — which is why an unconfigured terminal reports a null TID rather
   * than the adapter inventing one.
   */
  terminalId: string | null;
  merchantId: string | null;
  open: TerminalChannelFactory;
  /** Mint a fresh 12-character `pos_ref_no`. Sales and voids both draw on it. */
  nextRef: () => Promise<string>;
  now: () => Date;
  /** The operator stamp, when the till sends none. */
  cashier?: string | null;
  /**
   * The read deadlines, overridable.
   *
   * `TERMINAL_TIMEOUTS` is the park's, and a test that wanted to prove the
   * "no final answer" branch against the real budget would sit for two minutes
   * doing nothing — so the budget is a dependency, exactly as the print queue's
   * retry delay is. Nothing in production passes one.
   */
  timeouts?: { saleMs?: number; probeMs?: number };
}

export function ghlTerminal(deps: GhlDeps): PaymentTerminal {
  const { deviceId, label } = deps;
  const saleMs = deps.timeouts?.saleMs ?? TERMINAL_TIMEOUTS.customerInteractionMs;
  const probeMs = deps.timeouts?.probeMs ?? TERMINAL_TIMEOUTS.probeMs;

  async function withChannel<T>(fn: (channel: TerminalChannel) => Promise<T>): Promise<T> {
    const channel = await deps.open();
    try {
      return await fn(channel);
    } finally {
      await channel.close().catch(() => {
        // The exchange is already decided by here. A port that will not close
        // tidily must not turn an approved tender into a failure.
      });
    }
  }

  function blank(
    attemptId: string,
    requestedSatang: number,
    outcome: TerminalOutcomeKind,
    text: string,
    startedAt: number,
    extra: Partial<TerminalResult> = {},
  ): TerminalResult {
    return {
      attemptId,
      deviceId,
      protocol: 'ghl_linkpos',
      outcome,
      requestedSatang,
      approvedSatang: null,
      terminalRef: null,
      tranRef: null,
      invoiceNo: null,
      approvalCode: null,
      last4: null,
      tid: null,
      mid: null,
      qrPayload: null,
      responseCode: null,
      responseText: text,
      elapsedMs: Date.now() - startedAt,
      at: deps.now().toISOString(),
      ...extra,
    };
  }

  function tradeTypeFor(request: {
    tender: TerminalSaleRequest['tender'];
    wallet?: string | null;
  }): string {
    if (request.tender === 'card') return GHL_CARD_TRADE_TYPE;
    const named = request.wallet?.trim().toUpperCase();
    if (named) return named;
    // The park's QR tender on this dialect is Thai QR; a wallet tender with no
    // wallet named is a request the cloud has not finished filling in.
    if (request.tender === 'qr') return 'THAIQRCODE';
    throw new TerminalError(
      'TERMINAL_BAD_REQUEST',
      'a wallet tender has to name its wallet — ALIPAY, WECHATPAY, TRUEMONEY, DOLFIN, QRCS',
    );
  }

  /**
   * Read one answer and turn it into a result.
   *
   * A frame that will not parse is NOT a decline. Whether the money moved is
   * unknown from here, and `no_response` is the outcome that says so — the one
   * that blocks the till and starts the inquiry rule.
   */
  function readAnswer(
    request: { attemptId: string; amountSatang: number },
    /**
     * `transactionType` is both the vendor's word and the discrimination the
     * amount rule below needs, which is why it is a union and not a string.
     */
    sent: { tradeType: string; transactionType: 'SALE' | 'QUERY' | 'VOID'; ref: string },
    frame: Uint8Array | null,
    startedAt: number,
  ): TerminalResult {
    if (!frame) {
      return blank(
        request.attemptId,
        request.amountSatang,
        'no_response',
        'the terminal gave no final answer inside the customer-interaction budget',
        startedAt,
        // THE REFERENCE SURVIVES A SILENCE. It is what a wallet QUERY is keyed
        // on, so an attempt recorded without it could never be chased.
        { terminalRef: sent.ref },
      );
    }
    let fields: GhlFields;
    try {
      fields = parseGhl(decoder.decode(frame));
    } catch (err) {
      return blank(
        request.attemptId,
        request.amountSatang,
        'no_response',
        `the terminal's answer could not be read: ${err instanceof Error ? err.message : String(err)}`,
        startedAt,
        { terminalRef: sent.ref },
      );
    }
    const echoed = fields.pos_ref_no ?? '';
    if (echoed && echoed !== sent.ref) {
      /**
       * "***For POS, to ensure the pos_ref_no from request and response are
       * matched" (p.8). An answer about somebody else's transaction tells us
       * nothing about ours, so it is inconclusive rather than a decline.
       */
      return blank(
        request.attemptId,
        request.amountSatang,
        'no_response',
        `the terminal answered about ${echoed}, not about ${sent.ref}`,
        startedAt,
        { terminalRef: sent.ref },
      );
    }
    const verdict = interpretGhl(
      sent.tradeType,
      sent.transactionType,
      fields.response_code,
      fields.response_msg,
    );
    const approvedSatang = ghlSatang(fields.amount);
    let outcome = verdict.outcome;
    /**
     * The amount check, on integers, after the round-trip — ON A SALE ONLY.
     *
     * The vendor has a code for a partial approval and it is not the only way
     * one can arrive: an approval that simply comes back for less is the same
     * event and must take the same branch — refuse the sale and void the
     * tender — because the platform cannot take the difference.
     *
     * A QUERY and a VOID answer with an amount that is the terminal's own. A
     * void echoes what it took back, which after a partial approval is the
     * approved amount and not the amount the sale asked for; a QUERY may be
     * sent with no amount at all (`TerminalInquiryRequest.amountSatang` is
     * optional and defaults to `0` at the call below). Either of those read as
     * a shortfall would report a successful rescue as the thing it rescued
     * from — `partial_approval`, which the cloud answers with a void.
     */
    if (
      sent.transactionType === 'SALE' &&
      outcome === 'approved' &&
      approvedSatang !== null &&
      approvedSatang !== request.amountSatang
    ) {
      outcome = 'partial_approval';
    }
    return {
      attemptId: request.attemptId,
      deviceId,
      protocol: 'ghl_linkpos',
      outcome,
      requestedSatang: request.amountSatang,
      approvedSatang,
      terminalRef: sent.ref,
      /**
       * The void key on this dialect is the EDC's invoice number, so that is
       * what goes in `tran_ref`; the wallet hosts' own `transaction_id` is
       * carried beside it where there is one.
       */
      tranRef: fields.invoice_no || fields.transaction_id || null,
      invoiceNo: fields.invoice_no || null,
      approvalCode: fields.card_approval_code || null,
      last4: last4Of(fields.card_no),
      tid: fields.terminal_id || deps.terminalId,
      mid: fields.merchant_id || deps.merchantId,
      qrPayload: null,
      responseCode: ghlCode(fields.response_code),
      responseText: verdict.text,
      elapsedMs: Date.now() - startedAt,
      at: deps.now().toISOString(),
    };
  }

  return {
    deviceId,
    label,
    protocol: 'ghl_linkpos',

    async sale(request) {
      const startedAt = Date.now();
      const tradeType = tradeTypeFor(request);
      const serviceType =
        tradeType === GHL_CARD_TRADE_TYPE
          ? ''
          : request.qrDirection === 'scan'
            ? 'SCAN'
            : 'SHOWQR';
      if (serviceType === 'SCAN' && GHL_SHOWQR_ONLY.includes(tradeType)) {
        throw new TerminalError(
          'TERMINAL_BAD_REQUEST',
          `${tradeType} is show-QR only on this terminal (support matrix, p.12)`,
        );
      }
      const ref = await deps.nextRef();
      assertRef(ref);
      const xml = encodeGhlRequest({
        trade_type: tradeType,
        pos_ref_no: ref,
        amount: ghlAmount(request.amountSatang),
        transaction_type: 'SALE',
        service_type: serviceType,
        cashier: request.cashier ?? deps.cashier ?? '',
      });
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(encoder.encode(xml));
        request.onProgress?.({
          kind: 'sent',
          attemptId: request.attemptId,
          deviceId,
          at: deps.now().toISOString(),
        });
        const frame = await channel.readFrame(ghlFrameScanner, saleMs);
        return readAnswer(
          request,
          { tradeType, transactionType: 'SALE', ref },
          frame,
          startedAt,
        );
      });
    },

    async inquire(request: TerminalInquiryRequest) {
      const startedAt = Date.now();
      const tradeType = tradeTypeFor(request);
      if (tradeType === GHL_CARD_TRADE_TYPE) {
        /**
         * Refused before a byte goes out, and this is the whole reason the
         * staff-confirmation dialog exists.
         *
         * "Use Case ***Cannot QUERY for trade type CARD" (p.13). There is no
         * message to send. Inventing one — a QUERY the terminal would answer
         * about nothing, or a second SALE — would either mislead or charge the
         * guest twice.
         */
        return blank(
          request.attemptId,
          request.amountSatang ?? 0,
          'unsupported',
          'LinkPOS has no QUERY for a card sale (p.13) — a person has to read the terminal',
          startedAt,
        );
      }
      const xml = encodeGhlRequest({
        trade_type: tradeType,
        // The ORIGINAL sale's reference: the QUERY is keyed on it
        // ("Same as Original Sale", p.13), so a fresh one would ask about a
        // transaction that never existed.
        pos_ref_no: request.terminalRef,
        invoice_no: request.tranRef ?? '',
        transaction_type: 'QUERY',
        cashier: request.cashier ?? deps.cashier ?? '',
      });
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(encoder.encode(xml));
        const frame = await channel.readFrame(ghlFrameScanner, probeMs);
        const result = readAnswer(
          { attemptId: request.attemptId, amountSatang: request.amountSatang ?? 0 },
          { tradeType, transactionType: 'QUERY', ref: request.terminalRef },
          frame,
          startedAt,
        );
        /**
         * A QUERY that answers `01` means the terminal has no such
         * transaction, not that a sale was declined — and the difference
         * decides whether the till may take the money again. There is no
         * documented "still pending" code on this dialect; that is an open
         * question for GHL.
         */
        if (result.outcome === 'declined') {
          return { ...result, outcome: 'not_found' as const };
        }
        return result;
      });
    },

    async void(request: TerminalVoidRequest) {
      const startedAt = Date.now();
      const tradeType = tradeTypeFor(request);
      if (tradeType === 'THAIQRCODE') {
        // "***Only Thai QR Code is unable to be voided" (p.15). A refusal here
        // rather than a frame the terminal would reject.
        return blank(
          request.attemptId,
          request.amountSatang,
          'unsupported',
          'Thai QR cannot be voided on this terminal (p.15)',
          startedAt,
        );
      }
      if (tradeType === GHL_CARD_TRADE_TYPE && !request.approvalCode) {
        throw new TerminalError(
          'TERMINAL_BAD_REQUEST',
          'a card void needs the approval code as well as the invoice number (p.16)',
        );
      }
      // A FRESH reference for the void itself (pp.16-17); the sale is found by
      // its invoice number.
      const ref = await deps.nextRef();
      assertRef(ref);
      const xml = encodeGhlRequest({
        trade_type: tradeType,
        pos_ref_no: ref,
        amount: ghlAmount(request.amountSatang),
        invoice_no: request.tranRef,
        transaction_type: 'VOID',
        card_approval_code: request.approvalCode ?? '',
        cashier: request.cashier ?? deps.cashier ?? '',
      });
      return withChannel(async (channel) => {
        channel.discard();
        await channel.write(encoder.encode(xml));
        const frame = await channel.readFrame(ghlFrameScanner, probeMs);
        return readAnswer(
          request,
          { tradeType, transactionType: 'VOID', ref },
          frame,
          startedAt,
        );
      });
    },

    async settle() {
      // No verified transaction-level settlement wire contract is supplied.
      // Digio section 5.12 uses non-BER tags SA..SP; GHL specifies no settle.
      return { outcome: 'unsupported' as const, deviceId: deps.deviceId,
        errorCode: 'TERMINAL_SETTLEMENT_UNSUPPORTED', lines: [] };
    },
    async health() {
      const checkedAt = deps.now().toISOString();
      /**
       * OURS. The document describes no health, status or echo message of any
       * kind, so the probe is the least harmful thing that gets an answer: a
       * QUERY for a reference no sale ever used. The terminal answers `01` (no
       * such transaction) and that answer is the proof it is there.
       */
      const xml = encodeGhlRequest({
        trade_type: 'THAIQRCODE',
        pos_ref_no: GHL_PROBE_REF,
        transaction_type: 'QUERY',
        cashier: deps.cashier ?? '',
      });
      try {
        return await withChannel(async (channel) => {
          channel.discard();
          await channel.write(encoder.encode(xml));
          const frame = await channel.readFrame(ghlFrameScanner, probeMs);
          if (!frame) {
            return {
              reachability: 'unreachable' as const,
              serialNumber: null,
              softwareVersion: null,
              tid: deps.terminalId,
              mid: deps.merchantId,
              lastError: 'the terminal answered nothing',
              checkedAt,
            };
          }
          const fields = parseGhl(decoder.decode(frame));
          return {
            reachability: 'reachable' as const,
            serialNumber: null,
            softwareVersion: null,
            // A QUERY response is the only place this dialect carries them
            // (p.14), so a probe that comes back is also an identity check.
            tid: fields.terminal_id || deps.terminalId,
            mid: fields.merchant_id || deps.merchantId,
            lastError: null,
            checkedAt,
          };
        });
      } catch (err) {
        return {
          reachability: 'unreachable' as const,
          serialNumber: null,
          softwareVersion: null,
          tid: deps.terminalId,
          mid: deps.merchantId,
          lastError: err instanceof TerminalError ? err.code : 'TERMINAL_UNREACHABLE',
          checkedAt,
        } satisfies TerminalHealth;
      }
    },
  };
}

function assertRef(ref: string): void {
  if (ref.length > GHL_POS_REF_MAX) {
    throw new TerminalError(
      'TERMINAL_BAD_REQUEST',
      `pos_ref_no "${ref}" is longer than the ${GHL_POS_REF_MAX} characters every LinkPOS message has room for`,
    );
  }
}
