/**
 * A PAX A920Pro that is not there (S2-10a).
 *
 * It answers the same `3E55` frames the real terminal answers — generated by
 * the same encoder, with the same §4 CRC — behind the same adapter, so what a
 * test proves here it proves about `digio.ts`. Three behaviours are the reason
 * this exists rather than a stub:
 *
 *  - **The two-response QR exchange.** Ask for the payload and the terminal
 *    sends `A18` first and `A3` when the guest has paid. A stub answering once
 *    would never exercise the read loop that has to keep reading.
 *  - **Silence.** `no_response` writes nothing back, which is the state the
 *    whole inquiry rule exists for, and no stub can have it.
 *  - **The void windows.** `205` "Transaction already settle" only happens
 *    after time has passed, which is what the panel's "Advance terminal clock"
 *    is for.
 *
 * The wallet responses of §5.4.2.4 are NOT implemented: the park's wallet
 * tenders are not in this ticket, and a table guessed from a section whose own
 * heading contradicts its body would be worse than the terminal's own "function
 * is not support".
 */

import {
  TerminalError,
  type SimulatedOutcome,
  type SimulatedOutcomeOptions,
  type SimulatedTransaction,
  type TerminalChannel,
  type TerminalSimulator,
  type TerminalSimulatorEvent,
  type TerminalSimulatorEventKind,
  type TerminalSimulatorOptions,
} from './contract';
import {
  DIGIO_PAYMENT_TYPES,
  DIGIO_RESPONSE,
  decodeDigioFrame,
  digioAmount,
  digioFrameScanner,
  digioSatang,
  encodeDigioFrame,
  encodeTlv,
  readTlv,
  type DigioTlv,
} from './digio';
import { loopbackChannel } from './serial-channel';

/** Masked by the terminal before we ever see it, and a placeholder here (tag `09`). */
const SIM_MASKED_PAN = '424242******4242';
/** A cardholder name, because the real `A1` carries one and it must be dropped (tag `0A`). */
const SIM_CARD_HOLDER = 'TEST CARDHOLDER';

export interface DigioSimulatorOptions extends TerminalSimulatorOptions {
  answerDelayMs?: number;
  /**
   * The void password this terminal expects.
   *
   * Configuration, exactly as it is on the adapter's side: the vendor prints
   * one in its specification and that does not make it a constant of ours. A
   * simulator built with none refuses every void, which is the same answer a
   * real terminal gives to a wrong one.
   */
  voidPassword?: string | null;
  /** The software version `T1` reports. */
  softwareVersion?: string;
}

export function createDigioSimulator(options: DigioSimulatorOptions): TerminalSimulator {
  const now = options.now ?? (() => new Date());
  const keep = options.keep ?? 20;
  const settlementHour = options.settlementHourLocal ?? 23;
  const tzOffsetMinutes = options.timezoneOffsetMinutes ?? 420;
  const log: TerminalSimulatorEvent[] = [];
  const taken: SimulatedTransaction[] = [];
  let outcome: SimulatedOutcome = 'approved';
  let outcomeOpts: SimulatedOutcomeOptions = {};
  let clockSkewMs = 0;
  let serial = 0;

  /**
   * The identity this terminal reports on tags `13`/`14` (and `16`/`17` on a
   * QR response).
   *
   * Derived from the serial number when no TID is configured, because that is
   * the park's actual position: neither PAX has a TID or MID on file
   * (`DEVICE_INVENTORY.md:40-41`), and the first thing a real terminal does is
   * tell us — which is why the box writes it back onto the device row.
   */
  const tid = options.terminalId ?? options.serialNumber?.slice(-8) ?? 'SIMTID01';
  const mid = options.merchantId ?? 'SIMULATEDMID';

  const at = (): string => new Date(now().getTime() + clockSkewMs).toISOString();

  function note(kind: TerminalSimulatorEventKind, detail: Record<string, unknown> = {}): void {
    log.push({ at: at(), kind, detail });
    if (log.length > keep * 4) log.splice(0, log.length - keep * 4);
  }

  /** `YYYYMMDD` and `hh:mm` on the terminal's own clock (tags `11`/`12`, `14`/`15`). */
  function stamps(): { date: string; time: string; compact: string } {
    const local = new Date(Date.parse(at()) + tzOffsetMinutes * 60_000);
    const yyyy = String(local.getUTCFullYear());
    const mm = String(local.getUTCMonth() + 1).padStart(2, '0');
    const dd = String(local.getUTCDate()).padStart(2, '0');
    const hh = String(local.getUTCHours()).padStart(2, '0');
    const mi = String(local.getUTCMinutes()).padStart(2, '0');
    const ss = String(local.getUTCSeconds()).padStart(2, '0');
    return {
      date: `${yyyy}${mm}${dd}`,
      time: `${hh}:${mi}`,
      compact: `${yyyy.slice(2)}${mm}${dd}${hh}${mi}${ss}`,
    };
  }

  /**
   * `TID(8)+yyMMddHHmmss(12)+random(4)` — the format the document fixes for the
   * transaction id, and the key a void is made with.
   *
   * The last four are a counter rather than randomness so that a fixture
   * generated from this simulator is the same bytes every time it is generated;
   * a real terminal's four are random and nothing reads them.
   */
  function nextTranRef(): string {
    serial += 1;
    return `${tid.padEnd(8, '0').slice(0, 8)}${stamps().compact}${String(serial).padStart(4, '0')}`;
  }

  function nextApproval(): string {
    return `R${String(serial).padStart(5, '0')}`;
  }

  function settledSince(transactionAt: string): boolean {
    const local = (iso: string): Date => new Date(Date.parse(iso) + tzOffsetMinutes * 60_000);
    const from = local(transactionAt);
    const to = local(at());
    const boundary = new Date(from.getTime());
    boundary.setUTCHours(settlementHour, 0, 0, 0);
    if (boundary.getTime() <= from.getTime()) boundary.setUTCDate(boundary.getUTCDate() + 1);
    return to.getTime() >= boundary.getTime();
  }

  function send(emit: (bytes: Uint8Array, afterMs?: number) => void, entries: DigioTlv[]): void {
    const frame = encodeDigioFrame(encodeTlv(entries));
    note('response', tapeOf(entries));
    emit(frame, options.answerDelayMs ?? 0);
  }

  /**
   * What a response puts on the tape, and it is not the response.
   *
   * The tape is read by a Console panel through `TerminalController.events`
   * and can be copied out of one into a ticket, so it is a place a card
   * number could end up: an `A1` carries a masked PAN on tag `09` and the
   * cardholder's name on tag `0A`, and hex is not something a redactor
   * downstream can sweep. So the frame is emitted without ever being written
   * down, and the tape carries what a panel needs instead — which action
   * answered, with what code, for how much, against which reference and which
   * transaction.
   */
  function tapeOf(entries: DigioTlv[]): Record<string, unknown> {
    const by = fields(entries);
    const action = by['21'] ?? '';
    const detail: Record<string, unknown> = { action };
    if (by['22']) detail.responseCode = by['22'];
    if (by['01']) detail.amount = by['01'];
    if (by['04']) detail.ref = by['04'];
    // Tag `05` is the transaction id on every response this terminal sends
    // except `T1`, where it is the software version — the same moving-tag
    // problem `DIGIO_TAGS` exists for, in miniature.
    if (by['05'] && action !== 'T1') detail.tranRef = by['05'];
    return detail;
  }

  function fields(entries: DigioTlv[]): Record<string, string> {
    const out: Record<string, string> = {};
    for (const entry of entries) out[entry.tag] = entry.value;
    return out;
  }

  /**
   * The payload the terminal mints for a QR sale.
   *
   * NOT an EMVCo code. The simulator is not a PromptPay issuer and cannot mint
   * a string a bank would honour, so it says what it is: the plumbing proved by
   * it is that the payload reaches our own display and is rendered there, which
   * is the whole of the acceptance criterion. The real one arrives on this same
   * tag `QR`, and it is long enough to need a BER long-form length — which this
   * one is too, so the parser meets the same shape either way.
   */
  function qrPayloadFor(ref: string, tranRef: string, satang: number): string {
    return [
      'SIMULATED-EMVCO-PAYLOAD',
      `mid=${mid}`,
      `tid=${tid}`,
      `ref=${ref}`,
      `amount=${satang}`,
      `tranRef=${tranRef}`,
      'note=this-code-is-not-payable-and-exists-to-prove-the-display-path',
    ].join('|');
  }

  function handleSale(
    request: Record<string, string>,
    emit: (bytes: Uint8Array, afterMs?: number) => void,
  ): void {
    const ref = request['04'] ?? '';
    const paymentType = request['05'] ?? DIGIO_PAYMENT_TYPES.card;
    const requested = digioSatang(request['01']) ?? 0;

    if (outcome === 'no_response' || outcome === 'inquiry_unavailable') {
      note('withheld', { because: outcome, ref, paymentType });
      return;
    }
    if (outcome === 'timeout') {
      // The terminal is alive and its own host is not: `401 Host timeout`
      // (§6.2). A different fact from silence, and the till treats it as one.
      send(emit, [
        { tag: '21', value: paymentType },
        { tag: '22', value: DIGIO_RESPONSE.HOST_TIMEOUT },
        { tag: '04', value: ref },
        { tag: '01', value: digioAmount(requested) },
      ]);
      return;
    }
    if (
      paymentType !== DIGIO_PAYMENT_TYPES.card &&
      paymentType !== DIGIO_PAYMENT_TYPES.qr
    ) {
      // §5.4.2.4's wallet tables are not implemented here, and `202 Function is
      // not support` is the document's own word for a terminal that will not do
      // what it was asked.
      note('refused', { reason: 'this simulator does not do wallet tenders', paymentType });
      send(emit, [
        { tag: '21', value: paymentType },
        { tag: '22', value: DIGIO_RESPONSE.FUNCTION_UNSUPPORTED },
        { tag: '04', value: ref },
        { tag: '01', value: digioAmount(requested) },
      ]);
      return;
    }
    if (outcome === 'declined') {
      send(emit, [
        { tag: '21', value: paymentType },
        // §6.2 documents `2xx` as "transaction error code returned by Bank" and
        // enumerates only five of them, none of which is a plain decline. `200`
        // is inside the range the document defines and outside the five it
        // names.
        { tag: '22', value: '200' },
        { tag: '04', value: ref },
        { tag: '01', value: digioAmount(requested) },
      ]);
      return;
    }

    const approved =
      outcome === 'partial'
        ? (outcomeOpts.approvedSatang ?? Math.max(0, requested - 100))
        : requested;
    const tranRef = nextTranRef();
    const approvalCode = outcomeOpts.approvalCode ?? nextApproval();
    const when = stamps();
    remember({
      ref,
      tranRef,
      approvalCode,
      amountSatang: approved,
      kind: paymentType,
      at: at(),
      voided: false,
    });

    if (paymentType === DIGIO_PAYMENT_TYPES.card) {
      sendCardResponse(emit, { ref, tranRef, approvalCode, approved, when });
      return;
    }

    /**
     * The QR pair. `A18` goes first when the sale asked for the payload (tag
     * `06` = `02`), then `A3` when the guest has paid — and both are written
     * before this function returns, because a serial line does not care that
     * the adapter has not read the first one yet.
     */
    if (request['06'] === '02') {
      send(emit, [
        { tag: '21', value: 'A18' },
        { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
        { tag: '01', value: digioAmount(requested) },
        { tag: '04', value: ref },
        { tag: '05', value: tranRef },
        { tag: '06', value: DIGIO_PAYMENT_TYPES.qr },
        { tag: '14', value: when.date },
        { tag: '15', value: when.time },
        { tag: '16', value: tid },
        { tag: '17', value: mid },
        { tag: 'QR', value: qrPayloadFor(ref, tranRef, requested) },
      ]);
    }
    send(emit, [
      { tag: '21', value: DIGIO_PAYMENT_TYPES.qr },
      { tag: '04', value: ref },
      { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
      { tag: '01', value: digioAmount(approved) },
      { tag: '05', value: tranRef },
      { tag: '14', value: when.date },
      { tag: '15', value: when.time },
      // On an `A3` the TID is tag `16` and the MID tag `17`; on an `A1` they
      // are `13` and `14`. The same two facts, two tag numbers.
      { tag: '16', value: tid },
      { tag: '17', value: mid },
      { tag: '18', value: mid },
    ]);
  }

  function sendCardResponse(
    emit: (bytes: Uint8Array, afterMs?: number) => void,
    txn: {
      ref: string;
      tranRef: string;
      approvalCode: string;
      approved: number;
      when: { date: string; time: string };
    },
  ): void {
    send(emit, [
      { tag: '21', value: DIGIO_PAYMENT_TYPES.card },
      { tag: '01', value: digioAmount(txn.approved) },
      { tag: '04', value: txn.ref },
      { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
      { tag: '05', value: txn.tranRef },
      { tag: '06', value: txn.approvalCode },
      { tag: '07', value: '00' },
      { tag: '08', value: 'Visa Credit' },
      /**
       * The two fields that must never leave the box.
       *
       * They are here precisely so that the adapter is seen dropping them: the
       * parser keeps four digits of tag `09` and nothing of tag `0A`, and the
       * redaction fixture is built from this frame.
       */
      { tag: '09', value: SIM_MASKED_PAN },
      { tag: '0A', value: SIM_CARD_HOLDER },
      { tag: '0B', value: String(serial).padStart(6, '0') },
      { tag: '0D', value: 'A0000000031010' },
      { tag: '0E', value: '01' },
      { tag: '11', value: txn.when.date },
      { tag: '12', value: txn.when.time },
      { tag: '13', value: tid },
      { tag: '14', value: mid },
      { tag: '15', value: String(serial).padStart(2, '0') },
      { tag: '17', value: txn.tranRef.slice(-12) },
      { tag: '18', value: '6800' },
      { tag: '19', value: '80A0048000' },
      { tag: '20', value: 'Chip Online Pin' },
    ]);
  }

  function handleInquiry(
    request: Record<string, string>,
    emit: (bytes: Uint8Array, afterMs?: number) => void,
  ): void {
    const ref = request['04'] ?? '';
    if (outcome === 'inquiry_unavailable' || outcome === 'no_response') {
      /**
       * The terminal does not answer the inquiry either.
       *
       * On this dialect that is a fault; on the NEXGO it is the protocol. Both
       * end in the same place — a person reading the terminal's own screen and
       * an audited confirmation — which is why one word covers both.
       */
      note('withheld', { because: outcome, action: 'T2' });
      return;
    }
    const wanted = request['05'];
    const found = taken.find((entry) => (wanted ? entry.tranRef === wanted : false));
    if (!found) {
      // §5.13.2: `T3` with `203`, echoing the inquiry's own reference.
      send(emit, [
        { tag: '21', value: 'T3' },
        { tag: '22', value: DIGIO_RESPONSE.NOT_FOUND },
        { tag: '04', value: ref },
      ]);
      return;
    }
    /**
     * "the response follows with a sale message response" (§5.13.2) — the
     * terminal re-sends the SALE response, not a `T3`, and it carries the same
     * transaction id and approval code as the answer that was lost. That is
     * what lets the cloud settle the attempt it already has instead of charging
     * the guest a second time.
     */
    const when = stamps();
    if (found.kind === DIGIO_PAYMENT_TYPES.card) {
      sendCardResponse(emit, {
        ref,
        tranRef: found.tranRef,
        approvalCode: found.approvalCode ?? nextApproval(),
        approved: found.amountSatang,
        when,
      });
      return;
    }
    send(emit, [
      { tag: '21', value: DIGIO_PAYMENT_TYPES.qr },
      { tag: '04', value: ref },
      { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
      { tag: '01', value: digioAmount(found.amountSatang) },
      { tag: '05', value: found.tranRef },
      { tag: '14', value: when.date },
      { tag: '15', value: when.time },
      { tag: '16', value: tid },
      { tag: '17', value: mid },
      { tag: '18', value: mid },
    ]);
  }

  function handleVoid(
    request: Record<string, string>,
    emit: (bytes: Uint8Array, afterMs?: number) => void,
  ): void {
    const ref = request['04'] ?? '';
    const wanted = request['05'] ?? '';
    const refuse = (code: string, reason: string): void => {
      note('refused', { reason, code, tranRef: wanted });
      send(emit, [
        { tag: '21', value: 'A11' },
        { tag: '22', value: code },
        { tag: '04', value: ref },
      ]);
    };
    if (!options.voidPassword || request['06'] !== options.voidPassword) {
      // Never logged, never echoed. The tape says a password was wrong and not
      // what was sent.
      refuse(DIGIO_RESPONSE.PROCESSING_ERROR, 'the void password does not match');
      return;
    }
    const found = taken.find((entry) => entry.tranRef === wanted);
    if (!found) {
      refuse(DIGIO_RESPONSE.NOT_FOUND, 'no such transaction id');
      return;
    }
    if (found.voided) {
      refuse(DIGIO_RESPONSE.ALREADY_VOIDED, 'already voided');
      return;
    }
    if (found.kind === DIGIO_PAYMENT_TYPES.qr) {
      /**
       * "This request allows only Credit Card, Alipay and WeChat … EDC will
       * send response code '333'" (§5.5). The document elsewhere prints an
       * `A13` "Void QR Thai STD" response, which contradicts its own prose;
       * the conservative read is the one that matches GHL's flat "only Thai QR
       * Code is unable to be voided", and Digio have been asked.
       */
      refuse(DIGIO_RESPONSE.VOID_UNSUPPORTED, 'a Thai QR sale cannot be voided');
      return;
    }
    if (settledSince(found.at)) {
      refuse(DIGIO_RESPONSE.ALREADY_SETTLED, 'the batch has settled since this sale');
      return;
    }
    found.voided = true;
    const when = stamps();
    send(emit, [
      { tag: '21', value: 'A11' },
      { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
      { tag: '04', value: ref },
      { tag: '01', value: digioAmount(found.amountSatang) },
      { tag: '05', value: found.tranRef },
      { tag: '11', value: when.date },
      { tag: '12', value: when.time },
      { tag: '13', value: tid },
      { tag: '14', value: mid },
    ]);
  }

  function handleInfo(
    request: Record<string, string>,
    emit: (bytes: Uint8Array, afterMs?: number) => void,
  ): void {
    send(emit, [
      { tag: '21', value: 'T1' },
      { tag: '22', value: DIGIO_RESPONSE.SUCCESS },
      { tag: '04', value: request['04'] ?? '' },
      { tag: '05', value: options.softwareVersion ?? '1.8.127' },
      { tag: '06', value: options.serialNumber ?? tid },
    ]);
  }

  function remember(entry: SimulatedTransaction): void {
    taken.push(entry);
    if (taken.length > keep) taken.splice(0, taken.length - keep);
  }

  function handle(frame: Uint8Array, emit: (bytes: Uint8Array, afterMs?: number) => void): void {
    const request = fields(readTlv(decodeDigioFrame(frame)));
    const action = request['21'] ?? '';
    note('request', { action, ref: request['04'] });
    switch (action) {
      case 'A0':
        return handleSale(request, emit);
      case 'A10':
        return handleVoid(request, emit);
      case 'T2':
        return handleInquiry(request, emit);
      case 'T0':
        return handleInfo(request, emit);
      default:
        note('refused', { reason: `no such action code: ${action}` });
    }
  }

  return {
    deviceId: options.deviceId,
    label: options.label,
    protocol: 'digio_tlv',
    get outcome() {
      return outcome;
    },
    setOutcome(next, opts = {}) {
      outcome = next;
      outcomeOpts = opts;
      note('outcome.set', { outcome: next, approvedSatang: opts.approvedSatang ?? null });
    },
    advanceClock(minutes) {
      clockSkewMs += minutes * 60_000;
      note('clock.advanced', { minutes, clockSkewMs });
    },
    connect(): TerminalChannel {
      let buffer = new Uint8Array(0);
      return loopbackChannel((bytes, emit) => {
        const merged = new Uint8Array(buffer.length + bytes.length);
        merged.set(buffer);
        merged.set(bytes, buffer.length);
        buffer = merged;
        for (;;) {
          const span = digioFrameScanner(buffer);
          if (!span) return;
          const frame = buffer.slice(span.start, span.end);
          buffer = buffer.slice(span.end);
          try {
            handle(frame, emit);
          } catch (err) {
            /**
             * A frame this terminal cannot read is dropped and noted, never
             * answered. A real terminal has `002 Invalid format` for it, but it
             * cannot reply to a frame whose reference it could not read — and
             * an answer carrying a reference we invented would be worse than
             * silence.
             */
            note('refused', {
              reason: err instanceof TerminalError ? err.message : String(err),
              code: err instanceof TerminalError ? err.code : 'unknown',
            });
          }
        }
      });
    },
    transactions: () => taken.slice(),
    events: (limit = keep * 2) => log.slice(-limit),
  };
}
